### ISSUE TITLE
After update to 1.18.2 no Citizen Names are shown anymore

### ISSUE THREAD

**Issue by cynicalmax** [CitizensDev/Citizens2#2788] opened 2022-04-16 18:22 UTC
### `/version` output

```txt
[20:16:18 INFO]: This server is running Paper version git-Paper-289 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1cfd363)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
[20:16:56 INFO]: Citizens version 2.0.29-SNAPSHOT (build 2518)
[20:16:56 INFO]: Website: http://www.citizensnpcs.co
[20:16:56 INFO]: Author: fullwall
```

### Log file

https://pastebin.com/XKcrFPm4

### config.yml

https://pastebin.com/p9kMA07s

### saves.yml

https://pastebin.com/sEwEm1BJ

### Description

Hey there!

I´ve been upgrading from 1.18.1 to 1.18.2 and now my NPCs wont show their names anymore.
I upgraded most of my plugins to the latest version but it wont work.
In the config all names are shown!

Thanks in advance!
cynicalmax

**Comment by mcmonkey4eva** [comment] 2022-04-16 23:03
Confirmed replication, bug exists in latest dev build on 1.18.2 - hologram nameplates don't render.

I suspect it's caused by:

https://github.com/CitizensDev/Citizens2/commit/b0f1290b58839e8f97bfac9345ba5192d8edd2aa#diff-15bb6825fe83d3dc86ee999d6fa37bab28e16841153306dd36dff34488f66910R135

The armor stand changes included in that commit set `npc.data().set(NPC.NAMEPLATE_VISIBLE_METADATA, false);` on all 'point entity' holograms, which is valid for SIT animation holograms, but incorrect for nameplate holograms.

**Comment by ofunny** [comment] 2022-04-17 01:26
Confirmed, compared the configs with backup and they are fine. Must be related to the code. I can not replicate it on all of my servers, two server are fine after the upgrade, one shows a value starting with "CIT- ..." instead of the NPC name, and another server shows nothing or "Armorstand" instead of the name.

**Comment by mcmonkey4eva** [comment] 2022-04-17 05:44
Should be fixed in build DEV-2519+ thanks to commit https://github.com/CitizensDev/Citizens2/commit/da76924041d2791115c492a14e4396d595bfcb4d

**Closed by mcmonkey4eva** 2022-04-17 05:44 UTC
Labels: Confirmed Bug
