### ISSUE TITLE
Citizens AI wont allow them to go through open doors.

### ISSUE THREAD

**Issue by Jonathon594** [CitizensDev/Citizens2#979] opened 2016-11-22 08:24 UTC
Not sure if this can be fixed. I spent a long time today incorporating NPC's into my plugin. I set the target position to the players position but they avoid open doors as if they cant pass through.

**Comment by fullwall** [comment] 2016-11-22 08:36
Are you using the new or old pathfinder?

**Comment by Jonathon594** [comment] 2016-11-22 09:16
Minecraft 1.11, Not sure which pathfinder is being used. Is that in Citizens main config? (As far as I know everything is freshly generated, as I have deleted citizens folder before update)

**Comment by fullwall** [comment] 2016-11-22 09:18
It's 'use-new-finder' in the config, but it's probably false. I can't reproduce this, can you screenshot what your path looks like? It might also help to use 'debug-pathfinding'.

**Comment by Jonathon594** [comment] 2016-11-22 09:27
I set it to use new pathfinding. They can go through doors now, but not every time, sometimes they just get jammed up behind the wall next to the door. Is it correct to use, npc.getNavigator().setTarget(fp.getLocation()); (fp = Player) in the run() method of a trait?
![2016-11-22_03 26 45](https://cloud.githubusercontent.com/assets/1895876/20518114/9af121c4-b063-11e6-840b-39ae0e803f73.png)

**Comment by fullwall** [comment] 2016-11-22 09:29
You should probably do setTarget(fp.getLocation().getRelative(1, BlockFace.DOWN)) or setTarget(fp, false). What does debug-pathfinding show?

**Comment by Jonathon594** [comment] 2016-11-22 09:32
![2016-11-22_03 31 46](https://cloud.githubusercontent.com/assets/1895876/20518296/46838306-b064-11e6-939e-c8f0341d94e6.png)

it looks pretty bad. Not sure what its trying to tell me though, its spamming flowers everywhere I go.

**Comment by fullwall** [comment] 2016-11-22 09:33
Hmm OK - the flowers are showing where it's trying to go (clientside only). I'll try a bit more and see what I can fix.

**Comment by Jonathon594** [comment] 2016-11-22 09:35
Alot of the times they will go through the door, and with a little nudging I can get through if they hang up. Its usable now. If they have a straight path from the start they will go through, but if they get hung up on a wall they just sit there.

**Comment by fullwall** [comment] 2016-11-22 09:37
Yeah, this is with the new pathfinder right?

**Comment by Jonathon594** [comment] 2016-11-22 09:38
Correct

**Comment by mcmonkey4eva** [comment] 2016-11-22 09:48
Side question: what version of Citizens (build #) are you on?

**Comment by Jonathon594** [comment] 2016-11-22 10:13
build 1426

**Comment by mcmonkey4eva** [comment] 2016-11-22 10:37
Does the issue persist on build 1433 or higher from http://ci.citizensnpcs.co/job/Citizens2/ ?

**Comment by Jonathon594** [comment] 2016-11-22 10:49
Yea they still get stuck sometimes.

**Comment by mcmonkey4eva** [comment] 2016-11-22 10:52
You said:
`npc.getNavigator().setTarget(fp.getLocation()); (fp = Player) in the run() method of a trait?`
That should probably be, in addition to earlier corrections, run at most twice a second.
Ideally even less often than that.
The `run()` method runs every tick: 20 times a second. That could be the source of some issues.

**Comment by Jonathon594** [comment] 2016-11-22 10:55
Would, setTarget(player, false), and cancelNavigation(). I think I noticed in testing setting an entity target persisted until updating.

**Comment by Nutty101** [comment] 2016-12-09 17:52
Running into this as well, it's with the old path finder.  Trapdoors, gates all work, but the wooden doors and the iron door it refuses to go through it.  They also seem to have something with flowerpots and will walk to them and stop. Kinda odd.

**Comment by Nutty101** [comment] 2016-12-11 05:39
The doors are working on the new pathfinder, just the old refuses any door. Gates, and trapdoors are fine on both as well. Just checked in 1455 as well 1.10 / 1.11

**Closed** 2018-03-15 09:16 UTC
