### ISSUE TITLE
Citizens wont start anymore

### ISSUE THREAD

**Issue by RedbearPlayz** [CitizensDev/Citizens2#1801] opened 2019-05-30 02:30 UTC
- Citizens wont start on my server anymore
- this is the start error https://pastebin.com/M8P29ffJ
- It was working before so i went down 1 version and it still isnt working, i didnt do anything it was working completely fine though

The output of command `/version` on my server is: **(This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT))**
The output of command `/version citizens` on my server is: **(Citizens version 2.0.24-SNAPSHOT (build 1591)**

**Comment by mergu** [comment] 2019-05-30 02:34
This is a duplicate of several dozen closed issues. It can be solved by updating both Spigot and Citizens:
Spigot: https://www.spigotmc.org/wiki/buildtools/ OR https://papermc.io/downloads#Paper-1.13
Citizens: https://ci.citizensnpcs.co/job/Citizens2/

**Closed** 2019-05-30 02:50 UTC
