### ISSUE TITLE
New NPC Type: Client-Side

### ISSUE THREAD

**Issue by GamerSick** [CitizensDev/Citizens2#2804] opened 2022-05-27 16:36 UTC
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

1. This feature is really important for the future of minecraft servers (mostly rpgs), as usage of packets has increased a lot and benefit a lot in terms of performance impact on server resources.

2. Players won't benefit anything from this but server owners/plugin developers (especially BetonQuest) would be able to make per-player  NPCs who follow them through distances/quests.

3. Haven't found any other npc plugin to make this possible/ I'm not a very good dev to code an add-on :(

**Comment by mcmonkey4eva** [comment] 2022-05-27 19:13
Duplicate of https://github.com/CitizensDev/Citizens2/issues/2486 
note my comment there that tells you how you can do it today with either Java code or a Denizen script if you want to

**Closed by mcmonkey4eva** 2022-05-27 19:13 UTC
