### ISSUE TITLE
Baby Zombies drift North East

### ISSUE THREAD

**Issue by FlaggedBrad** [CitizensDev/Citizens2#754] opened 2016-04-19 05:02 UTC
Hi, it seems that having a baby zombie spawn in (on plugin load) makes it drift in the negative x and z coordinates. The plugin saves this data and loads it on next server restart(making it drift more)
[YouTube Video showing simulated server restarts](https://youtu.be/YDTqVmbscRc)

[saves.yml](http://pastie.org/10803143) and [config.yml](http://pastie.org/10803145)

Minecraft & Citizens version:
![image](https://cloud.githubusercontent.com/assets/18545011/14628114/b769f498-05af-11e6-88c5-d5da3730e09b.png)

**Comment by mcmonkey4eva** [comment] 2016-04-19 06:01
Please update your server, this is an issue most likely caused by outdated versions.
Minecraft 1.9.2 is out. Failing that, 1.8.8 is an option too.

**Comment by fullwall** [comment] 2016-04-19 10:58
There was a bug fix around this drifting in slightly more recent builds so you would have to double check if it is fixed in more recent builds.

**Comment by FlaggedBrad** [comment] 2016-04-20 05:17
the zombies still drift after i updated the server and citizens plugin to these versions: 
![image](https://cloud.githubusercontent.com/assets/18545011/14664092/73026524-067c-11e6-8caf-ecff75a8557e.png)

**Comment by fullwall** [comment] 2016-05-18 10:18
Try with newest build

**Closed** 2016-05-22 10:53 UTC
