### ISSUE TITLE
b1336 startup error

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#690] opened 2016-03-20 02:56 UTC
```
it-Spigot-f04e043-622014a (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
Citizens version 2.0.17-SNAPSHOT (build 1336)
```

i get this at startup:
```
[22:40:25] [Server thread/WARN]: java.lang.Throwable: Unexpected NavigationListener add
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:138)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$2.run(Citizens.java:296)
[22:40:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[22:40:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[22:40:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:40:25] [Server thread/WARN]: java.lang.Throwable: Unexpected NavigationListener add
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:138)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[22:40:25] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$2.run(Citizens.java:296)
[22:40:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[22:40:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[22:40:25] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[22:40:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
 this happens when i /home heads (next to another npc, in an area/chunk not loaded at startup) and every time i go there (/back) (same thing if server restarted and login form opposite place)
```
[22:41:09] [Server thread/INFO]: leasoncre issued server command: /home heads
[22:41:09] [Server thread/WARN]: java.lang.Throwable: Unexpected NavigationListener add
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.spawn(EventListen.java:513)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:490)
[22:41:09] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:132)
[22:41:09] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
[22:41:09] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:41:09] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:55)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:136)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:76)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftWorld.getChunkAt(CraftWorld.java:128)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftWorld.getBlockAt(CraftWorld.java:92)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.utils.LocationUtil.isBlockDamaging(LocationUtil.java:242)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.utils.LocationUtil.isBlockUnsafeForUser(LocationUtil.java:228)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.now(Teleport.java:122)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.teleport(Teleport.java:201)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.teleport(Teleport.java:157)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.commands.Commandhome.goHome(Commandhome.java:95)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:49)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:456)
[22:41:09] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:366)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:41:09] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:41:09] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[22:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[22:41:09] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

nothing special about these npc's, only 2 on this test server, other than creating them, nothing has been done to them.

**Comment by mcmonkey4eva** [comment] 2016-03-20 03:43
Duplicate of https://github.com/CitizensDev/Citizens2/issues/689

**Closed by mcmonkey4eva** 2016-03-20 03:43 UTC
