### ISSUE TITLE
/npc lookclose does not move head up/down for non-player NPC types

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#3016] opened 2023-04-25 12:25 UTC
### `/version` output

```txt
This server is running Paper version git-Paper-514 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: dd216c1)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-468 (MC: 1.19.4)
```

### `/version Citizens` output

```txt
Citizens version 2.0.31-SNAPSHOT (build 3031)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/109216

### config.yml

https://paste.denizenscript.com/View/109217

### saves.yml

https://paste.denizenscript.com/View/109221

### Description

When enabling the lookclose of an NPC using `/npc lookclose` does the head rotate on the y-axis when following you, but not move up or down.

This only happens for non-player NPCs from what I tested so far using Zombie, Villager, Allay and Cat.
Only once I set the NPC to a Player did the head also follow me up and down, even tho Mobs such as Zombies can move their head in all directions too.

**Comment by fullwall** [comment] 2023-04-25 13:02
@Andre601 this is Minecraft behaviour. In recent builds it has become possible to alter this using e.g. /npc metadata set RESET_PITCH_ON_TICK false. I am happy to create a /npc command for this, but did you have a potential name to suggest?

**Comment by Andre601** [comment] 2023-04-25 13:11
Can't really think of one... Tho maybe have it as a flag in the lookclose command? Feels like the best place rather than a separate command.

i.e. `/npc lookclose --pitch` or smth like this?

**Comment by Andre601** [comment] 2023-04-25 13:31
I would assume they expect the NPC to move the head wherever you're currently are.

Also, kinda related to this: I've noticed that a default pose you set may not be returned to depending on where you exit the mob's lookclose range.

As an example, this is the default pose I've set for this Zombie NPC:
![2023-04-25_15 30 25](https://user-images.githubusercontent.com/11576465/234292617-be79a9d3-fade-4b8a-a9da-1d04932ec501.png)

When I exit to the left of the NPC is it returning to its default pose just fine:
![2023-04-25_15 29 40](https://user-images.githubusercontent.com/11576465/234292654-ee7f6759-61a5-4a29-80b9-70ee1429a69f.png)

But exiting to the right of it will not make it go back completely:
![2023-04-25_15 28 51](https://user-images.githubusercontent.com/11576465/234292710-3afccfd4-70fd-4232-8007-3b321d645b16.png)

I can make a video if this, if preferred.

**Comment by fullwall** [comment] 2023-04-25 13:32
What are you using to reset the pose? Or default pose?

**Comment by Andre601** [comment] 2023-04-25 13:37
I simply set a pose as default using `/npc pose --default <name>`

**Comment by fullwall** [comment] 2023-05-28 17:09
Going to close this since I think it was resolved / not reproducible on discord.

**Closed by fullwall** 2023-05-28 17:09 UTC
