### ISSUE TITLE
NPC names being truncated

### ISSUE THREAD

**Issue by Lurkrul** [CitizensDev/Citizens2#1870] opened 2019-07-15 14:08 UTC
The output of command `/version` on my server is: **(PLEASE FILL IN)**
[10:02:59] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-9a643a6-2349feb (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
[10:04:26] [Server thread/INFO]: Citizens version 2.0.25-SNAPSHOT (build 1730)

This is a fresh server with just Citizens on it, creating an npc called 12345678901234567890 results in an npc with the nametag 56789012345678

When it first spawns in it has the correct name tag, then it immediately changes to the shortened version

**Comment by mcmonkey4eva** [comment] 2019-07-18 04:55
Confirmed this, I believe it's broken by https://github.com/CitizensDev/Citizens2/commit/673ee025428a610197a6e228fec02f7d15a91a30

**Comment by mcmonkey4eva** [comment] 2019-07-18 17:13
Update:
The problem is this: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/trait/ScoreboardTrait.java#L32-L41
is removing the NPC from the scoreboard team, thus breaking NPC scoreboard-backed functionality.
I believe fullwall mistook "entry" for being scoreboard tags - in reality "entry" is who's on the team.

Scoreboard tags are a different system, which, despite the name, are set on the entity, not the scoreboard. The proper method to use would be this: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#addScoreboardTag-java.lang.String-

**Comment by mcmonkey4eva** [comment] 2019-07-18 17:22
Should be fixed in build 1731+ https://ci.citizensnpcs.co/job/Citizens2/

**Closed by mcmonkey4eva** 2019-07-18 17:22 UTC
Labels: Bug Report, Work To Do
