### ISSUE TITLE
Kicked from server for "Invalid Player Move Packet Received" inconsistently when using any kind of teleport. Issue stops when essentials or citizens is removed.

### ISSUE THREAD

**Issue by Sealflipper** [CitizensDev/Citizens2#2836] opened 2022-07-25 23:57 UTC
### `/version` output

```txt
his server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
[25.07 22:30:30] [Server] You are running the latest version
[25.07 22:30:30] [Server] Previous versiongit-Paper-78 (MC: 1.19)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2633)
[25.07 22:31:19] [Server] [INFO] Website: http://www.citizensnpcs.co
[25.07 22:31:19] [Server] [INFO] Author: fullwall
```

### Log file

N/A

### config.yml

https://paste.denizenscript.com/View/99387

### saves.yml

https://paste.denizenscript.com/View/99388

### Profiler report

N/A

### Description

No error in the console. Players are inconsistently kicked whenever they use any kind of teleport after the 1.19 update. Teleports include /tp, /tpa, /warp, /spawn, /rtp, and even nether portals. The kick they get is for: "Invalid player move packet received".

There is no error logs in console.

I found that when removing either essentials or citizens the problem goes away. 

I found another server owner who also has had the same bug as me. I tested every other plugin we shared between us, but no others fixed the issue when they were removed. The other server owner kick events happened less on their server than mine. We both had similar sizes of RAM and no issue with tps for our servers. They were a smaller server though. 

We imported the other server owners' files on a test server, but couldn't confirm if the bug was present or not because it was much more of a rare occurrence for him. I tried testing my essentials and citizen
[server133597 - 25 Jul 2022 17_30_0.zip](https://github.com/CitizensDev/Citizens2/files/9185494/server133597.-.25.Jul.2022.17_30_0.zip)
s

**Comment by mcmonkey4eva** [comment] 2022-07-26 00:04
`Log file

N/A`
No.

Post your full `logs/latest.log` to https://paste.denizenscript.com/New/Log as the template said to

**Comment by GriffinCodes** [comment] 2022-07-26 21:40
We are also receiving this issue. Discussed a bit with electroniccat in #paper-help if you want to read it. [With this patch applied](https://gist.github.com/electronicboy/29555c6ddb57d72ab9d62552b09d0ca5), this is our log: https://paste.denizenscript.com/View/99432

What seems to be happening is Citizens is modifying the `awaitingPositionFromClient` variable, setting it to null.

It's only happening after this commit in paper: https://github.com/PaperMC/Paper/commit/5deafd1969b3c521af9cabb46822ecb01e6ce498

![image](https://user-images.githubusercontent.com/12417961/181117119-f14a650a-a1c9-492d-b50b-a8b9d6d7a1c9.png)

**Comment by Sealflipper** [comment] 2022-07-27 00:48
Here is my latest log. Hope it can help
https://paste.denizenscript.com/View/99443

**Comment by fullwall** [comment] 2022-07-27 05:19
I'm a little confused as to how this occurs to be honest, awaitingPositionFromClient is null on the player's packet listener

**Comment by fullwall** [comment] 2022-07-27 05:35
So I'm unable to reproduce this and there's no plausible explanation I can see for Citizens to affect a Player's packet listener

**Comment by Tomhoran628** [comment] 2022-07-27 05:37
I too am having this issue. Purpur 1.19. Was able to narrow it down to citizens.

**Comment by mcmonkey4eva** [comment] 2022-07-27 05:45
@GriffinCodes
A: please replicate on Paper, not whatever that is.
B: Your custom debug output seems to be outputting non-null values from Citizens every time, and non-null when you got disconnected, only going null later eg when rebooting.

-----

@Sealflipper 
Your log doesn't seem to contain replication of the issue?


-----

@Tomhoran628 if it's a Purpur problem, it's a purpur problem. Citizens supports Spigot and Paper, we can't really make guarantees about anything else, for obtuse forks like Purpur either they need to fix it on their end or need to go out of their way to help plugins patch when relevant. I'd strongly recommend you stick to Paper.

**Comment by Chiruso** [comment] 2022-07-27 06:04
I got this problem too with CMI /spawn command using Paper 1.19 #81. I removed the plugin (2.0.30 b2639) and now everything seems to work fine

**Comment by BillyGalbreath** [comment] 2022-07-27 09:23
Hi there, one of the Purpur devs here. :wave:

> either they need to fix it on their end or need to go out of their way to help plugins patch when relevant

Just wanted to touch base to let you know we have been looking into this issue since the first builds of 1.19 came out, and I can assure you this is not caused by anything Purpur has done. If it was we would have contacted you to work out a fix (as we have done with other major plugin developers in the past), or if it was our fault for breaking compatibility we would have fixed it on our own (we pride ourselves in staying 100% compatible with Paper while still offering all the features and configurations we do).

Side note:

> not whatever that is [...] obtuse forks like Purpur

Even though we are the 3rd largest server software in Bukkit land, we are very clearly acute :wink: 

![image](https://user-images.githubusercontent.com/332527/181211895-d5b57806-3e39-44b3-acff-17a4f945129e.png)

**Comment by fullwall** [comment] 2022-07-27 09:48
Thanks for your insight. I'm not sure of the cause of this issue either from a cursory look at minecraft source. Could be related to mounted entities although I didn't see any issues in testing. 

I think mcmonkey was making a comment on the diversity of server software and behaviour (case in point Paper changing API behaviour to also teleport mounts). although I note your comments on compatibility.

**Comment by Sealflipper** [comment] 2022-07-27 09:49
Hi,
I run solely on paper
@mcmonkey4eva I’m sorry, I just looked at the log and you don’t see any players get kicked on it with this issue. I’m away from my computer right now, but I will provide you a better log later today.

**Comment by OnionsBoot** [comment] 2022-07-27 12:33
I just wanted to add that I'm also getting these player kicks. I have only seen them from home teleportation and warp teleportation offered by EssentialsX, but not from RTP (I use a plugin from a different developer for RTP.) I run on Purpur 1.19. I wonder if it has something to do with Citizens + EssentialsX?

Example of console log from a little while ago: [08:00:50 INFO]: OnionBoots lost connection: Invalid move player packet received. 

Nothing else referencing this in the console pops up when this occurs.

**Comment by mcmonkey4eva** [comment] 2022-07-27 13:12
This issue thread is full of a lot of unrelated posts at this point, so I've marked as off-topic all the posts that either A: claim replication but don't include a log, or B: just aren't relevant to the issue. (You can still view these comments by clicking 'show comment', they're just hidden by default to keep the issue focused)

---

If you're coming here to post that you're seeing the same issue, please:
- Post your full logs/latest.log to https://paste.denizenscript.com/New/Log
- make sure you're replicating on Paper or Spigot, not any other fork
- make sure the log you post contains the bug happening
- if you're able to consistently replicate it, please test with latest Paper, latest Citizens, and all other plugins removed, and if it still happens post a log from that

**Comment by Blast-MC** [comment] 2022-07-27 17:27
> @GriffinCodes A: please replicate on Paper, not whatever that is.
Hi there, other dev here. Parchment is our small paper fork that adds some interfaces for easier plugin development and exposes some things to the API like insomnia and Sound Events, but most importantly, we **do not touch anything relative to teleportation, nor do we have any obscure performance enhancements.** This fork is purely for enhanced plugin development on our server. We started experiencing this issue after updating to the Teleportation API patch from upstream paper, and removing Citizens immediately stops any strange kicking behavior.

> B: Your custom debug output seems to be outputting non-null values from Citizens every time, and non-null when you got disconnected, only going null later eg when rebooting.
The null outputs are after a player is teleported properly, that value is set back to null. When a wrongful teleport happens, the log outputs invalid (see [line 5201](https://paste.denizenscript.com/View/99432#5201)). Right above it, the value is set, but somewhere in between the client receiving the ClientboundPlayerPositionPacket and sending back the ServerboundAcceptTeleportationPacket, the value is set back to null and thus the invalid value kicks the player.

**Comment by BehrRiley** [comment] 2022-07-27 17:44
> Parchment is our small paper fork that adds some interfaces for easier plugin development and exposes some things to the API like insomnia and Sound Events, but most importantly, we do not touch anything relative to teleportation, nor do we have any obscure performance enhancements.

The issue here is not what any higher fork does or doesn't do, it's that it's explicitly we cannot replicate the issue on our supported versions. If you can replicate the issue on a supported version, we can better reference what the actual cause may be. Again, as mcmonkey recommended:

If you're coming here to post that you're seeing the same issue, please:

-     Post your full logs/latest.log to https://paste.denizenscript.com/New/Log
-     make sure you're replicating on Paper or Spigot, **not any other fork**
-     make sure the log you post contains the bug happening
-     if you're able to consistently replicate it, please test with the latest Paper, latest Citizens, and all other plugins removed, and if it still happens post a log from that

**Comment by fullwall** [comment] 2022-07-27 18:32
Citizens does not touch the packet listener AFAIK so it's a bit mysterious

**Comment by Sealflipper** [comment] 2022-07-28 01:37
Here is an actual log with the kick happening. There is a couple of players at the bottom of this log that were kicked with the described issue.
https://paste.denizenscript.com/View/99480

**Comment by Sealflipper** [comment] 2022-07-28 01:38
Here is a log with the issue. It kicked a few players as described at the bottom
https://paste.denizenscript.com/View/99480

(I accidentally closed the issue my bad)

**Comment by BehrRiley** [comment] 2022-07-28 01:56
> Here is a log with the issue. It kicked a few players as described at the bottom
https://paste.denizenscript.com/View/99480

a cleanroom environment without any forks/plugin interactions would be a server with nothing but Citizens and Paper are utilized; optionally, returning those removed plugins to determine if they happen to cause a [**plugin conflict**](https://wiki.citizensnpcs.co/Plugin_Conflict).

Such as PluginManager - Plugin managers are dangerous and will cause unpredictable, including seemingly unrelated, issues.

WorldGuard also handles a lot of packet handling, it's very relevant in this case - whether you think it's doing anything or not.

You're also a version behind on a major release for Denizen from about a month ago - Latest Denizen stable release builds are at https://ci.citizensnpcs.co/job/Denizen/.

It may not hurt to also use the latest developmental Citizens version to determine if it resolves any problems you're experiencing - Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.

**Comment by nhanledev** [comment] 2022-07-28 14:16
/npc teleport in the same world is OK. but teleport to another world throws this error and the NPC just disappear

**Comment by fullwall** [comment] 2022-08-02 22:07
Going to close this issue until it can be replicated. https://github.com/PaperMC/Paper/issues/8222 seems to suggest that it is not Citizens specific.

**Closed by fullwall** 2022-08-02 22:07 UTC
Labels: Bug Report

**Comment by PaintsplattersMC** [comment] 2022-08-06 02:50
Hopefully your knowledge of how citizens and denizen works should show some light on why this conflict is happening?

i can verify the issue  can be caused by citizens + denizen (as least as 1 method) perhaps some API call is at fault?

this would explain why other plugins can cause this issue as well. it would be nice to know how denizen or citizens affects this.

the more insight to the problem the better

**Comment by Maitlans** [comment] 2022-08-06 03:17
I'm only having this issue when Denizen is installed on the server.  So when a clean copy of Denizen and Citizens are present nothing will happen but as soon as either you create a mirror NPC, or if I start up the server with Denizen using a script like this one, the issue will continue to happen.  Deleting said NPC does not fix the issue, you have to restart server for it to not happen. This is just what I've gathered from my testing.

```
Resource Pack Handler:
  type: world
  events:
    on player joins:
      - execute as_server "say hi"```

**Comment by mcmonkey4eva** [comment] 2022-08-06 04:52
If it relates to Denizen it would make more sense than Citizens - Denizen has a network interception tool (that is enabled when you do `mirrorskin` or similar) which could potentially muck with that data - I'm confused about the reports that don't include Denizen if that's the case though

**Comment by Sealflipper** [comment] 2022-08-06 05:26
Yes, I can confirm that removing denizen fixes the problem for me. I did update it like you recommended earlier, but that didn’t fix anything. I’m glad we have a lead on the issue now

**Comment by mcmonkey4eva** [comment] 2022-08-06 06:09
Update from investigation:

The kick (in relation to Denizen `mirrorskin` at least) results from `awaitingPositionFromClient` being null when the client sends `ServerboundMovePlayerPacket`

The client sends this packet in response to any `ClientboundPlayerPositionPacket`.

The vanilla server sends this packet only when `internalTeleport(...)` is called, which of course sets the awaitPos field and then sends the packet.

Thus, any invalid sending of this packet will cause this error.

An example of a likely invalid sending of the packet:
Paper patch `0181-Player.setPlayerProfile-API.patch`: https://github.com/PaperMC/Paper/blob/bef2c9d005bdd039f188ee53094a928e76bd8e59/patches/server/0181-Player.setPlayerProfile-API.patch#L134
Contains `connection.send(new net.minecraft.network.protocol.game.ClientboundPlayerPositionPacket(loc.getX(), loc.getY(), loc.getZ(), loc.getYaw(), loc.getPitch(), java.util.Collections.emptySet(), 0, false));`
This sends the packet without setting the field, meaning calls to that method will likely break replicate the error (I haven't tested this).

------

The reason Denizen causes a crash here is that Paper NMS is breakingly incompatible with Spigot NMS:

`internalTeleport` is a private method in vanilla. It is made public in Paper and called externally.

That means network interception tools like the one in Denizen will not properly intercept Paper-only calls to that method. Which means that they will call the wrong class instance because they are not intercepted.

The routes forward from here are:
A: Hardlock Denizen to require Paper (and any other network-intercepting plugins must as well)
B: Paper removes the incompatible NMS change, or
C: Some form of multifunctional mess that implements separate NMS for Spigot vs Paper, or uses dynamic codegen to build intercept classes.

From past experience I know Paper is oppositional to support NMS-based plugins, meaning B is unlikely to happen. A is not currently acceptable until Paper does a genuine hardfork. Means C is the best option, which will require looking into codegen hackery options.

**Comment by PaintsplattersMC** [comment] 2022-08-06 06:18
is there any eta of when this issue will be looked into being fixed?

i don't mean to be impatient. I'm simply wondering what priority this issue has

**Comment by mcmonkey4eva** [comment] 2022-08-06 07:31
> is there any eta of when this issue will be looked into being fixed?

It started being looked into the moment I finished tracing it.

It's fixed now, latest Denizen dev build (6368+) no longer replicates the bug for me: https://ci.citizensnpcs.co/job/Denizen_Developmental/

Required writing some utterly cursed dynamic codegen: https://github.com/DenizenScript/Denizen/blob/dev/plugin/src/main/java/com/denizenscript/denizen/utilities/packets/NetworkInterceptCodeGen.java

**Comment by Maitlans** [comment] 2022-08-06 17:04
Can confirm that the latest Denizen Dev Build fixes the issue for me.

**Comment by GriffinCodes** [comment] 2022-08-06 18:44
Also fixed for me
