### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by NoahUyttebroeck** [CitizensDev/Citizens2#2808] opened 2022-06-05 19:04 UTC
### `/version` output

```txt
This server is running CraftBukkit version 3493-Spigot-b081915-9d46b56 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
Checking version please wait...
You are 2 version(s) behind
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2557)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/97299

### config.yml

https://paste.denizenscript.com/View/97300

### saves.yml

https://paste.denizenscript.com/View/97301

### Description

When creating a npc with `CitizensAPI.getNPCRegistry().createNPC(EntityType.VILLAGER, name)` and later using the `npc.getNavigator().setTarget(loc);` the server crashes.

Description: Ticking entity
java.lang.IllegalArgumentException: Start element (9223367638808264704) is larger than end element (-9223372036854775808)
        at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1120)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1081)
	at net.minecraft.world.level.entity.EntitySectionStorage.a(SourceFile:55)
	at net.minecraft.world.level.entity.EntitySectionStorage.b(SourceFile:118)
	at net.minecraft.world.level.entity.LevelEntityGetterAdapter.a(SourceFile:42)
	at net.minecraft.world.level.World.a(World.java:828)
	at net.minecraft.world.level.IEntityAccess.b(SourceFile:62)
	at net.minecraft.world.level.ICombinedAccess.b(SourceFile:24)
	at net.minecraft.world.entity.Entity.h(Entity.java:1018)
	at net.minecraft.world.entity.Entity.a(Entity.java:764)
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:2703)
	at net.minecraft.world.entity.EntityLiving.h(EntityLiving.java:2658)
	at net.citizensnpcs.nms.v1_18_R2.entity.VillagerController$EntityVillagerNPC.h(VillagerController.java:242)
	at net.minecraft.world.entity.EntityLiving.w_(EntityLiving.java:3118)
	at net.minecraft.world.entity.EntityInsentient.w_(EntityInsentient.java:614)
	at net.minecraft.world.entity.EntityAgeable.w_(EntityAgeable.java:153)
	at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2808)
	at net.minecraft.world.entity.EntityInsentient.k(EntityInsentient.java:382)
	at net.minecraft.world.entity.npc.EntityVillager.k(EntityVillager.java:280)
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:804)
	at net.minecraft.world.level.World.a(World.java:700)
	at net.minecraft.server.level.WorldServer.lambda$9(WorldServer.java:401)
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54)
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:381)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1330)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047)
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mcmonkey4eva** [comment] 2022-06-06 01:11
That looks like some form of world file corruption?

**Comment by PikaMug** [comment] 2022-06-09 07:24
Target location could be too far away? https://bugs.mojang.com/browse/MC-218504

**Comment by NoahUyttebroeck** [comment] 2022-06-14 19:51
It isn't

**Comment by fullwall** [comment] 2022-06-19 14:53
Seems duplicate of #2810, please update to latest build and try replicate again.

**Closed by fullwall** 2022-06-19 14:53 UTC
