### ISSUE TITLE
NPC´s are rotating to same direction few numbers

### ISSUE THREAD

**Issue by alexhyperlapse** [CitizensDev/Citizens2#2020] opened 2020-01-07 19:54 UTC
NPC´s which i set to look at some directions after logout and login to server are all moved to one way. But just their body, not head. They are all players. Head look at same way which i set but body not.
The output of command `/version` on my server is: 1.15
The output of command `/version citizens` on my server is: 2.0.26 1.15 EARLY ALPHA 4
![image](https://user-images.githubusercontent.com/12379608/71924670-be3d6380-318f-11ea-99e3-125d441e25ca.png)

**Comment by mcmonkey4eva** [comment] 2020-01-07 19:56
Duplicate of https://github.com/CitizensDev/Citizens2/issues/1487

**Closed by mcmonkey4eva** 2020-01-07 19:56 UTC
