### ISSUE TITLE
NPCs teleporting but not spawning when using /npc tphere from a long distance

### ISSUE THREAD

**Issue by Elric02** [CitizensDev/Citizens2#2074] opened 2020-03-23 23:52 UTC
When teleporting a NPC from a location far away using /npc tphere, the NPC won't be visible until I disconnect and reconnect to the server, or reload the plugin. If I teleport to the npc using /npc tp while he isn't visible, it teleports me to his new correct location, the one after i did /npc tphere. So coords are updated but the npc does not get loaded.

The output of command `/version` on my server is: 
PaperSpigot 1.15.2 version 143
The output of command `/version citizens` on my server is: 
2.0.26 build 1852

**Comment by mcmonkey4eva** [comment] 2020-03-24 15:13
Confirmed and replicated.

Running on Spigot instead of Paper, `git-Spigot-6de3d4b-a6f8093 (MC: 1.15.2)`

Tested as described - create NPC, went far enough away that it despawned, then used `/npc tphere`... it teleported but did not spawn until I reloaded the area (by reconnecting) to force it to.

Debug logs for later reference:
```
mcmonkey4eva[/127.0.0.1:57289] logged in with entity id 142 at ([world]-123.80894943477618, 64.0, -107.15271167252754)
mcmonkey4eva issued server command: /npc create bob
Fetched profile d664f4b4-d688-4d28-9fbd-3d58ef2844b4 for player Bob
Removing 167 from skin tracker due to DespawnReason.PENDING_RESPAWN
Despawned 167 DespawnReason.PENDING_RESPAWN
mcmonkey4eva issued server command: /npc tphere
mcmonkey4eva lost connection: Disconnected
mcmonkey4eva left the game
Removing 167 from skin tracker due to DespawnReason.CHUNK_UNLOAD
Despawned 167 DespawnReason.CHUNK_UNLOAD
Despawned id 167 due to chunk unload at [-24,-6]
mcmonkey4eva[/127.0.0.1:57300] logged in with entity id 278 at ([world]-373.6347583008354, 68.0, -77.57048536049129)
Spawned id 167 due to chunk event at [-24,-6]
```

**Comment by Andre601** [comment] 2020-03-27 16:58
I have an issue, that may be related to this in a way, which is, that the yaw of the player is ignored when running `/npc tphere`
The pitch and location seem to be updated but the yaw is for whatever reason ignored and seems to default to 0. (looking south)

This wasn't the case with the version prior to the current release (2.0.26)

Versions:
Server: **git-Paper-146 (MC: 1.15.2)**
Citizens: **2.0.26-SNAPSHOT (build 1854)**

**Comment by fullwall** [comment] 2020-03-27 17:16
@Andre601 I have pushed a new build for you.

Regarding this issue - looks like the NPC isn't being treated as invalid for some reason?

**Comment by fullwall** [comment] 2020-03-27 17:20
Try the latest build

**Comment by Andre601** [comment] 2020-03-27 17:29
Receiving NPEs for latest build (1856)
https://paste.helpch.at/opeqemunuv.md

**Comment by fullwall** [comment] 2020-03-27 17:52
Apologies, try 1857

**Comment by Andre601** [comment] 2020-03-27 19:19
Can confirm that the yaw issue has been fixed with this build 👍

**Comment by mcmonkey4eva** [comment] 2020-04-06 18:55
This issue isn't fixed, the random second issue that Andre put inside this issue instead of separate is all that was fixed.
(For future reference, Andre: if it's not the same issue, make a separate issue post... "related" doesn't mean "same")

**Comment by Andre601** [comment] 2020-04-06 18:59
I'm sorry that someone else thought this was in any way fixed, instead of waiting for the author to respond.
Please find someone else to blame, thank you very much.

**Comment by mcmonkey4eva** [comment] 2020-05-12 13:40
This bug is currently being investigated and potential fixes tested.
Just in case it's needed for future reference, recording of full replication on a newly generated server: https://gfycat.com/illegalunconsciousbull

We've determined thus far that it's specifically caused by NPCs teleporting when they've despawned *for the player* but not *on the server*. ie teleporting an NPC from a far-away loaded chunk.
Teleporting an NPC from an unloaded chunk, or from a nearby loaded chunk, are both fine.

**Comment by fullwall** [comment] 2020-07-02 04:48
Is this fixed?

**Comment by mcmonkey4eva** [comment] 2020-07-02 14:50
Seems to be - can't replicate on build 2026 on Spigot 1.16.1

**Closed by mcmonkey4eva** 2020-07-02 14:50 UTC
Labels: Confirmed Bug, Research To Do
