### ISSUE TITLE
Pathfinding - Regions

### ISSUE THREAD

**Issue by Grafhugo** [CitizensDev/Citizens2#2631] opened 2021-08-08 17:47 UTC
The output of command `/version` on my server is: **(Paper spigot 1.16.5 - R0.1 -Snapshot**
The output of command `/version citizens` on my server is: *2.0.28 - Snapshot build 2357**

Problem:

I made type sheep npcs, used waypoint disableteleport and waypoint provider wander

now i want them to keep inside of their cage. If i open the Wooden-gate they should stay inside of it. I tried it with a /npc path - regions but that did not work, they ignored my border

**Comment by mcmonkey4eva** [comment] 2021-08-13 13:38
What regions did you define? Did you try a worldguard region? Is that region properly limited to *inside* the the area you want (if you include anything outside, even if the gate is excluded, they'll select a destination outside and pathfind through the gate).

If you can't resolve the issue on your own based on the above, please enable debug and pathfinding debug in your Citizens config, and replicate the issue (let the sheep wander out), then [Pastebin](https://paste.denizenscript.com/new/Log) the full `logs/latest.log`, and also post screenshots of the environment and the paths being selected.

**Comment by Grafhugo** [comment] 2021-08-13 13:58
The regions way i found out i  needed to klick some blocks, 

yes i also have a worldguard region, how can i incule that?

**Comment by mcmonkey4eva** [comment] 2021-08-13 14:13
While in the path editor, type `worldguardregion YOUR_REGION_NAME_HERE`

**Comment by Grafhugo** [comment] 2021-08-13 14:21
okey i will try that! Thanks!

**Comment by Grafhugo** [comment] 2021-08-13 21:09
On the Image you see the Gate,

the red blocks simbolise the Worldguard border, the npc is on the outside. The Pigs still cross the gate

![2021-08-13_23 08 06](https://user-images.githubusercontent.com/38762018/129418661-b4a02f5a-91b9-4929-b0f4-c15136965ac5.png)

**Comment by mcmonkey4eva** [comment] 2021-10-07 13:24
Closing due to lack of posting the requested information, and as there's no visible issue in your last post (the pig is right next to the blocks you used to mark your region...? that's working as intended... if you wanted the pig on the other side of the wall, put the region on the other side?)

**Closed by mcmonkey4eva** 2021-10-07 13:24 UTC
Labels: Waiting For Reply
