### ISSUE TITLE
UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#1693] opened 2019-02-05 08:24 UTC
Paper dev 516 (Spigot 1.13.2)
Citizens dev 1613

@fullwall Updated PaperSpigot and now noticing this error in console. Caused by this commit in Paper @zachbr
https://github.com/PaperMC/Paper/commit/28cf2696d4078643774b896fb6a9dcda0a35a8fd

All NPCs in my spawn spawned invisible. Reloading with ``/citizens reload``, only a few npcs spawned back and the error occurred again.

```
[00:20:19] [Server thread/WARN]: [Citizens] Task #116 for Citizens v2.0.24-SNAPSHOT (build 1613) generated an exception
java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.remove(CraftPlayer.java:1943) ~[patched_1.13.2.jar:git-Paper-516]
	at net.citizensnpcs.npc.AbstractEntityController.remove(AbstractEntityController.java:35) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.entity.HumanController.remove(HumanController.java:120) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:228) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:306) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-516]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-516]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

```
[00:24:48] [Server thread/INFO]: player issued server command: /citizens reload
[00:24:48] [Server thread/WARN]: java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
[00:24:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.remove(CraftPlayer.java:1943)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.remove(AbstractEntityController.java:35)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_13_R2.entity.HumanController.remove(HumanController.java:120)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:228)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.reload(Citizens.java:362)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:44)
[00:24:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:24:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:24:48] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:24:48] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
[00:24:48] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
[00:24:48] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:24:48] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[00:24:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[00:24:48] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:24:48] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[00:24:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[00:24:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcmonkey4eva** [comment] 2019-02-05 08:41
Duplicate of #1692

**Closed by mcmonkey4eva** 2019-02-05 08:41 UTC
