### ISSUE TITLE
Brown Panda type doesn't actually work

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#1847] opened 2019-06-27 16:33 UTC
The version of server and citizens:
http://cdn.hexedhero.com/u/OMktFh0v1P.jpg

**Comment by mcmonkey4eva** [comment] 2019-06-28 01:42
What?

**Comment by HexedHero** [comment] 2019-06-28 07:01
/npc panda --gene brown

Doesn't change the panda to brown

**Comment by mcmonkey4eva** [comment] 2019-06-28 07:19
What's the output in chat from the command?

**Comment by HexedHero** [comment] 2019-06-28 07:24
http://cdn.hexedhero.com/u/nW4bCohv9y.jpg

**Comment by mcmonkey4eva** [comment] 2019-06-28 07:40
Issue confirmed. I believe the cause is that `--hgene` option does nothing, due to "setMainGene" being used: https://github.com/CitizensDev/Citizens2/blob/bb42a99bb2826d57aea8b96f7a505f59bfc9b958/v1_14_R1/src/main/java/net/citizensnpcs/nms/v1_14_R1/trait/Commands.java#L201-L209 (ie it's the same as `--gene`)
(And I believe 'BROWN' is considered recessive, ie it requires both genes being set, not just one)

**Comment by mcmonkey4eva** [comment] 2019-06-28 08:28
Fixed by https://github.com/CitizensDev/Citizens2/commit/1028a3fabbc5ca758276c61e72cf8078d483b2de in Build 1709.
Use `/npc panda --gene brown --hgene brown`

**Closed by mcmonkey4eva** 2019-06-28 08:28 UTC
Labels: Bug Report, Work To Do
