### ISSUE TITLE
Skin change wont update

### ISSUE THREAD

**Issue by LimitedGames** [CitizensDev/Citizens2#949] opened 2016-10-23 20:45 UTC
(Please Dont close issues. Fix your plugin please, for minecraft 1.10 are not all plugins that are needed for my server!)

Minecraft Version: 1.8.7
Citizens version: 2.0.16
If i set a npc withe the name of a player, and the player will change his skin the npc wont update, after restart is also doesnt update. But if you set a new npc and give him the playername-skin it will be the new skin of the player, but it still doesnt update the first npc.

**Comment by mcmonkey4eva** [comment] 2016-10-24 00:53
Duplicate of https://github.com/CitizensDev/Citizens2/issues/947

"(Please don't spam issues. Fix your understanding please. For minecraft 1.8.7 there's no support.)"

**Closed by mcmonkey4eva** 2016-10-24 00:53 UTC
