### ISSUE TITLE
Phantoms don't look near

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#1845] opened 2019-06-27 14:31 UTC
The version of server and citizens:
http://cdn.hexedhero.com/u/OMktFh0v1P.jpg

Phantoms don't look at players with /npc look
simple.

**Comment by mcmonkey4eva** [comment] 2019-06-28 07:35
Issue confirmed. There appears to be a problem with Phantom rotation in general: when spawned, they're staring straight up into the sky, and nothing seems to be rotating them.
Using Denizen to forcibly rotate it with standard commands (teleport, etc) did work, though.

**Comment by HexedHero** [comment] 2019-07-01 05:28
Same issue with Dolphins

**Comment by mcmonkey4eva** [comment] 2019-07-01 09:37
Phantoms fixed by https://github.com/CitizensDev/Citizens2/commit/b66fe9d18afcb6899885b984abdac61d1c41a5f1 in build 1712+!
Not sure if Dolphins are fixed - if not please reply below and I'll reopen this

**Closed by mcmonkey4eva** 2019-07-01 09:37 UTC
Labels: Bug Report, Research To Do
