### ISSUE TITLE
TeleportStuckAction Broken on Latest Version

### ISSUE THREAD

**Issue by Korimaru** [CitizensDev/Citizens2#1604] opened 2018-10-29 18:53 UTC
I have a plugin running on my server that frequently sets the navigation target of citizens on the server. After updating to the 1.13.2 versions of Spigot and the Citizens API citizens do not navigate and the console is spammed with the following error: https://pastebin.com/K1KHxCwU
Was working with no problems in 1.12.
Citizens config: https://pastebin.com/KWaqk5b8

The output of command `/version` on my server is: CraftBukkit version git-Spigot-alba5fe-3359cbl (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1586)

**Comment by mcmonkey4eva** [comment] 2018-10-29 18:58
Please try with dev build 1589 http://ci.citizensnpcs.co/job/Citizens2/
The issue is likely fixed in that build (via commit https://github.com/CitizensDev/CitizensAPI/commit/fe418b53d9a84a732b910cadff88bb64d0a086d3 )

**Comment by Korimaru** [comment] 2018-10-30 15:18
Working great now, thanks!

**Closed** 2018-10-30 19:41 UTC
Labels: Waiting For Reply
