### ISSUE TITLE
Wither tries to fly up before following a path

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#751] opened 2016-04-16 22:00 UTC
Every time the path is updated, the wither flies up, waits a few seconds, THEN moves forward.

This makes it impossible to function when the pathfinder is updated too rapidly.

**Comment by fullwall** [comment] 2016-04-19 11:00
Can you get a screenshot of the path debug output?

**Comment by mcmonkey4eva** [comment] 2016-04-19 20:18
Here's a quick recording of it happening (default minecraft pathfinder): http://i.imgur.com/ZiZpW0t.gifv
Looks roughly the same with `use-new-finder` enabled.

**Comment by fullwall** [comment] 2016-04-21 16:30
@mcmonkey4eva I think this is caused by the tall grass in the way not being marked as passable. Can you try removing the grass?

**Comment by mcmonkey4eva** [comment] 2016-04-21 20:15
the NPC is actually in a clearing in that recording - there's tallgrass around it but not where the NPC is actually moving through.

**Comment by fullwall** [comment] 2016-06-05 11:27
Fixed

**Closed by fullwall** 2016-06-05 11:27 UTC
Labels: Bug Report
