### ISSUE TITLE
Disappear Villager

### ISSUE THREAD

**Issue by Thin-Troll** [CitizensDev/Citizens2#2821] opened 2022-06-26 21:30 UTC
### `/version` output

```txt
Purpur 1.17.1
```

### `/version Citizens` output

```txt
=====[ Citizens v2.0.30-SNAPSHOT (build 2596) ]=====
```

### Log file

none

### config.yml

https://paste.denizenscript.com/View/98071

### saves.yml

https://paste.denizenscript.com/View/98072

### Description

Villagers disappear, appear after reloading the Citizens plugin via /citizens reload

**Comment by mcmonkey4eva** [comment] 2022-06-26 22:46
Duplicate of another issue as you already figured out yourself

**Closed by mcmonkey4eva** 2022-06-26 22:46 UTC
