### ISSUE TITLE
latest spigot citizens build, citizens don't show up

### ISSUE THREAD

**Issue by vkaygaming** [CitizensDev/Citizens2#1818] opened 2019-06-09 23:02 UTC
am using the latest citizens spigot build and it seems to "create" my npcs but they are invisible

**Comment by mcmonkey4eva** [comment] 2019-06-10 00:04
likely dupe of #1790

**Closed by mcmonkey4eva** 2019-06-10 00:04 UTC

**Comment by vkaygaming** [comment] 2019-06-10 15:32
doubt it cuz i've never updated my java and citizens reload does nothing for me
