### ISSUE TITLE
NPC's Skin not Changing?

### ISSUE THREAD

**Issue by iKrypticHD** [CitizensDev/Citizens2#606] opened 2016-01-28 05:40 UTC
Every time I create a new NPC it just goes straight to the default Steve skin. So I try to do the /npc skin <name> on the NPC, but it doesn't work either. It just keeps the default Steve skin. This began to occur about 2-3 months ago. When I first installed the plugin to my server, it ran like a charm. But then one day I was passing the room that I had my NPCs in, and I realized none of them had the skin I gave them. They all had the default "Steve" skin. This issue is driving me INSANE!!! Does anyone know of a fix for this? Like I said, this all began to occur about 2-3 months ago. If anyone has any suggestions, let alone an actual FIX, then please let me know ASAP!

Appreciated! :)

-iKrypticHD

**Comment by mcmonkey4eva** [comment] 2016-01-28 21:17
Are you on shared hosting?

**Comment by iKrypticHD** [comment] 2016-01-28 21:21
Like what do you mean? If you mean do I run my server through another business, then yes I do. I have my server through BisectHosting.

**Comment by mcmonkey4eva** [comment] 2016-01-28 21:54
**googles name**
Yup, that's a shared host.

You need to not be on a shared host to fix that :/

The problem is, shared hosts sell the same machine to too many people, and it generates too many skin requests, and Citizens is programmed currently to not fight it much if Mojang blocks a skin request as part of their flood filter.

**Comment by Triliton** [comment] 2016-02-01 21:28
Could this be the case as where i can only load skins i allready have used now?
Cause i cant set any new skins anymore. If i choose a skin of a npc i allready have, it works.
If i create a new npc, and try to set a new skin name, it wont load.

**Comment by fullwall** [comment] 2016-02-02 06:21
You can save permanent skin snapshots by using /npc skin -p which will cut down on the number of skin requests.

**Comment by Triliton** [comment] 2016-02-06 21:42
Doesnt work with -p

**Comment by fullwall** [comment] 2016-02-08 05:37
The process should be (for example): set skin of 'fullwall' account to desired skin. Use /npc skin fullwall -p  ingame. Set skin of account to next skin. 

Are you doing this and it's not working?

**Comment by Triliton** [comment] 2016-02-11 15:47
unknown flag. I write /npc skin skinname, lets say /npc skin Triliton -p i get an error saying unknown flag

**Comment by mcmonkey4eva** [comment] 2016-02-11 18:51
@Triliton Make sure you're on latest 1.8.8 dev release.

**Comment by Triliton** [comment] 2016-02-11 20:21
My server is for 1.8, could the problem be more host related?

**Comment by mcmonkey4eva** [comment] 2016-02-11 20:35
1.8.8 and 1.8 are different things, you need to be on 1.8.8 not 1.8

**Comment by Triliton** [comment] 2016-02-13 14:33
Yes i know. But im on 1.8. I wont change til 1.8.8. So is there any way to fix this?

**Comment by mcmonkey4eva** [comment] 2016-02-13 23:28
Yeah... updating... ;-; OR moving to a non-shared host.

**Closed** 2016-03-03 21:49 UTC
