### ISSUE TITLE
Cannot change npc type

### ISSUE THREAD

**Issue by niho1212** [CitizensDev/Citizens2#1555] opened 2018-08-18 15:29 UTC
Here is the explanation of the problem:
I recently upgraded from 1.12.2 to 1.13 development build and I also installed Citizens, however, after I create an npc I am not able to change the entity/mob type of the npc, so whenever I attempt to do it I get an ingame and console error.

Step-by-step remaking the problem (screenshots):
[1] https://imgur.com/jSrqeET (/Version)
[2] https://imgur.com/2RmaK34 (/Version Citizens)
[3] https://imgur.com/Ex8QUeo (/Npc create npctest)
[4] https://imgur.com/rPCw0KO (/Npc type Vindicator)
[5] https://imgur.com/Pw85Jxl (Ingame error message)
[6] Console Error Log: https://pastebin.com/RKkEcpqJ (CONSOLE ERROR LOG)

**Comment by mcmonkey4eva** [comment] 2018-08-18 17:49
Related to https://github.com/CitizensDev/Citizens2/issues/1534

**Comment by fullwall** [comment] 2018-08-19 06:41
Can't reproduce this, seems like a plugin or reload issue. Which plugins are you using?

**Comment by fullwall** [comment] 2018-09-11 06:33
Can you try without MergedMob/Ridables?

**Comment by mcmonkey4eva** [comment] 2018-09-24 17:44
Please reply below with updated information (based on last support replies) if the issue persists, and I'll re-open the issue.

**Closed by mcmonkey4eva** 2018-09-24 17:44 UTC
