### ISSUE TITLE
Massive amounts of objects being created

### ISSUE THREAD

**Issue by Kneesnap** [CitizensDev/Citizens2#1464] opened 2018-03-30 01:43 UTC
We have a major memory leak issue in Citizens. With Citizens it brings our TPS down to 10, without Citizens it is a solid 20, and our memory does not fluctuate. From our profiler:

![YourKit Object Allocation](https://i.imgur.com/yJw9bTB.png)

PaperSpigot Version:
This server is running Paper version git-Paper-1169 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
You are 204 version(s) behind

Citizens Version:
Citizens v2.0.22-SNAPSHOT (build 1528)

Server Specs:
32GB RAM
Intel i7 4790k 4Ghz

NPC Count: 443

**Comment by mergu** [comment] 2018-03-30 13:07
`You are 204 version(s) behind` 🤔
1) Update before posting an issue.
2) Test on Spigot, not Paper.

**Comment by fullwall** [comment] 2018-03-30 13:15
Thank you for the profiling data. However, you are recording allocations here which is not really a memory leak. Is the problem with garbage collection or memory leaks?

**Comment by Kneesnap** [comment] 2018-04-01 05:19
Paper is not updated because we wish to support 1.12 and 1.12.X, and ProtocolSupport is not an option. We can test on regular Spigot though. It may not be a leak, but it's a lot of objects getting allocated, and the garbage collector causes a lag-spike when it cleans all of this stuff up. As for which pathfinder we're using, I'm unsure how to check that.

**Comment by fullwall** [comment] 2018-04-01 16:47
Try latest build. Pathfinder is in config.yml

**Comment by Kneesnap** [comment] 2018-04-02 01:16
Seems to have fixed the advancement issue, although there are still a lot of objects being allocated by other things.

![Another YourKit Log](https://i.imgur.com/nTJFjq8.png)

As for the pathfinder, I still don't see it in config.yml. I've uploaded it instead.

```yml
# Citizens Configuration

npc:
  chat:
    options:
      bystanders-hear-targeted-chat: false
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '&7<npc>: &f<text>'
      with-target-to-bystanders: '&7<npc>: &f<text>'
      to-target: '&7<npc>: &f<text>'
      with-targets-to-bystanders: '&7<npc>: &f<text>'
  default:
    lookclose: {}
    pathfinding:
      range: 25.0
    talkclose: {}
    look-close:
      enabled: true
      range: 4
    random-talker: false
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 3
    text:
      '0': Hello!
  limits:
    default-limit: 20
    max-permission-checks: 10
    max-speed: 100
    max-packet-entries: 15
  chunks:
    always-keep-loaded: false
  selection:
    quick-select: true
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  text:
    max-talk-cooldown: 180
    min-talk-cooldown: 60
    talk-item: '*'
  pathfinding:
    use-new-finder: true
    attack-range: 3.0625
    new-finder-open-doors: false
    default-distance-margin: 2
    update-path-rate: 40
    maximum-new-pathfinder-iterations: 50000
  server-ownership: false
  controllable:
    use-boat-controls: true
  packets:
    update-delay: 40
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest: true
    view-distance: 100.0
    use-latest-by-default: false
  tablist:
    disable: true
  teleport-delay: -1
  player-scoreboard-teams:
    enable: true
storage:
  database:
    driver: ''
    password: ''
    url: ''
    username: ''
  savetask: {}
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
general:
  colorscheme: {}
  translation:
    locale: ''
  debug-mode: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  debug-pathfinding: false
  debug-file: ''
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
economy:
  npc:
    cost: 100.0
subplugins:
  folder: plugins
advanced:
  check-minecraft-version: false
```

**Comment by mcmonkey4eva** [comment] 2018-04-02 01:33
`
    use-new-finder: true`
^ that's the relevant key. Might be worthwhile to test with it flipped to `false`.

**Comment by CrystallDEV** [comment] 2018-04-02 12:56
Since the new pathfinder was meant to be the improved version (regarding to the commit messages) I dont think that this would solve the error.
I guess that the new finder got tested and compared to the old one.

Might still be worth testing.

**Comment by mcmonkey4eva** [comment] 2018-04-02 17:31
@CrystallDEV the 'new finder' is a Citizens codebase implementation of a pathfinder, the 'old finder' is a linking to minecraft's pathfinder. They're two different options and when unsure it's best to test both and get your own comparisons.

**Comment by CrystallDEV** [comment] 2018-04-03 10:06
@mcmonkey4eva ah okay thanks for explaining

**Comment by Kneesnap** [comment] 2018-04-04 00:59
With ```use-new-finder: false```,

![New Settings](https://i.imgur.com/v2eLEPN.png)

**Comment by Kneesnap** [comment] 2018-04-05 09:04
This is much better than how it was before, as we have a constant 20 TPS, however it limits our total player-count per server because when lots of areas are loaded (from lots of players online), it is GCing very often.

**Comment by fullwall** [comment] 2018-04-09 11:26
What are your GC settings? May be worth trying to work on that. It's hard to tell from your screenshots the types of allocated objects and how often they are allocated.

**Comment by Kneesnap** [comment] 2018-04-16 00:00
```bash
RAM="6G"
java -Xms$RAM -Xmx$RAM -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=35 -XX:G1MaxNewSizePercent=60 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch -DIReallyKnowWhatIAmDoingISwear -DOfficialSetup -jar PaperSpigot.jar
```

**Comment by Kneesnap** [comment] 2018-04-17 22:49
@fullwall The type of objects being allocated are related to advancements. CriteronTrigger or something like that.

**Comment by Kneesnap** [comment] 2018-04-21 23:56
I would also like to point out these too, these appear to be more, unrelated problems.
![Here](https://i.imgur.com/08LaqCk.png)

**Comment by ryantheleach** [comment] 2018-05-01 01:13
How many citizens do you have in range of spawn? To get those sort of numbers It's my guess that you have to be using many of them in a lobby that's within range of the players joining and idling at the initial spawn point.

2091 avg objects per second on a UUID to string call, listed under entityJoinedWorld?

Unless I'm misunderstanding the screenshot... That's intense.

**Comment by Kneesnap** [comment] 2018-05-01 16:38
We do have a fair bit of NPCs (If I were to guess, probably close to 200) in our "spawn city", but our spawn city is vast and rarely fully loaded at once. Most of the NPCs are in parts of the area which is normally unloaded.

We have less than 500 total NPCs, and only started having this issue when we updated to 1.12. (Before we ran 1.9)

**Comment by CorporalBruno** [comment] 2018-05-01 17:44
6 GB RAM may not be enough to handle many players on the server along with 500 total npcs....

**Comment by Kneesnap** [comment] 2018-05-01 18:28
RAM amount isn't the problem, the issue still happens if we double the amount of RAM we use. The issue is Citizens is creating a bunch of "garbage" objects in memory which it only uses once. This accumulates over time, and fills up RAM with unused objects. Without the garbage objects, the amount of RAM citizens uses is not high.

These garbage objects are bad because garbage collection (the process which cleans the garbage up) creates a lag-spike when it cleans it all up. The solution is to perform operations without creating so many garbage objects. I gave an example above as to how to fix one of the several issues. I'd submit a pull request if there were build instructions for how to setup Citizens.

**Comment by CorporalBruno** [comment] 2018-05-01 19:08
To be specific the garbage collection process creates a lag spike when you use 12 GB ram?

**Comment by Kneesnap** [comment] 2018-05-01 19:31
The spikes still happen with 8, that's as far as we tested for spikes. (The spikes happen with more players online too, since some of the things that are creating the objects will create more if more players are online). We only tested 12GB on the test server, which did not have that many players. At that point we were testing what the source of the lag was. While we didn't have enough players on to test if the spike was observed, we saw the same problems in the profiler which caused it to have spikes at lower RAM amounts.

Doubling our RAM would likely increase the amount of players we could have per-server, but ultimately it would allow us more players per server (better scalability, better efficiency, etc) if Citizens took small easy steps to fix these problems. These problems are not present because "There are lots of NPCs", these problems are present because "The code that handles lots of NPCs is creating performance problems which can be fixed".

**Comment by mcmonkey4eva** [comment] 2018-05-02 04:17
For building Citizens:
Clone the repo (Citizens2 and if needed CitizensAPI)
Open projects using Maven (probably via IntelliJ handler or similar for simplicity)
Make sure you've built all Spigot versions (with BuildTools) listed in the various submodule pom files
(Feel free to locally edit the versions in the pom files to a different subversion if needed but don't commit the alteration, EG 1.10 and 1.10.2 can be swapped between safely. This change is handy if you have a different version available locally from what the pom lists)
You should at that point be able to edit code normally and build via Maven as normal (Note that in Citizens2 project, you build the parent module, which will include the submodules inherently.)

Also relevant note: The `Text` system in Citizens is rarely used realistically. It's quick and simple to setup, but not very capable for advanced usages. Most advanced users who want chatty NPCs will write their own scripts (via Denizen or similar) or own plugins as relevant.

**Comment by ryantheleach** [comment] 2018-05-02 06:49
>These problems are not present because "There are lots of NPCs", these problems are present because "The code that handles lots of NPCs is creating performance problems which can be fixed".

Sure, But It wasn't just the amount of NPC's that I was worried about, it was the amount of times that it seemed like entityJoinedWorld was being called.

An entity spawning isn't a lightweight operation regardless of what AI or NPC or plugins are involved. Thus why I was asking, the fact they are joining so much was worrying.

**Comment by mcmonkey4eva** [comment] 2018-05-02 06:58
`entityJoinedWorld` is not the spawn call, it's just an awkward label. It's actually the standard tick call.

Also: Citizens will (by default) spawn NPCs if they're visible, and despawn them if they're not. They don't spawn multiple times if visible to multiple players.

**Comment by ryantheleach** [comment] 2018-05-02 07:00
2091 permission checks per second, approximately 104 permission checks per tick. On the massive assumption that the text trait is checking every tick, that could be 104 entities checking 1 player, or 104 players being checked by 1 entity.

assuming that it's this line, 

https://github.com/CitizensDev/Citizens2/blob/184b414dd594d430247d3465dacfd37877c3c7a3/main/src/main/java/net/citizensnpcs/trait/text/Text.java#L186

https://github.com/CitizensDev/Citizens2/blob/184b414dd594d430247d3465dacfd37877c3c7a3/main/src/main/java/net/citizensnpcs/trait/text/Text.java#L148

we can see that it's checking a cooldown, (is your cooldown really low?(TALK_CLOSE_MAXIMUM_COOLDOWN and TALK_CLOSE_MINIMUM_COOLDOWN) )

and that the range of the entities is already checked.

@mcmonkey4eva Does (search instanceof Player) filter Players as opposed to 'humans/citizens/npcs?' https://github.com/CitizensDev/Citizens2/blob/184b414dd594d430247d3465dacfd37877c3c7a3/main/src/main/java/net/citizensnpcs/trait/text/Text.java#L137

Otherwise I don't really see how it could be optimized much further.

**Comment by mcmonkey4eva** [comment] 2018-05-02 07:09
`Player` is any player-type Entity, that does not separate out NPCs with entitytype Player.
That's an interesting point - perhaps that permissions bork is from NPCs trying to send text to other NPCs (which could very reasonably cause the permissions system to thrash a little as it was doing).

Very possible that ensuring NPCs won't be checked could help reduce waste here.

An additional optimization available there might be applying the cooldown even when the permission check fails (that way the permission check won't run every tick, and instead only run after the cooldown clears each time).
IE:
```java
if (!sendText(player)) return;
```
could just be:
```java
sendText(player);`
```
and work out better that way.

@fullwall

**Comment by BloodEko** [comment] 2018-05-02 10:48
It sounds like this line is running for every tick for every npc, checking for checking all server entities, filter them to players and then if possible send the chat message.

Basically the stuff when you walk arround and npcs chat to you ?https://github.com/CitizensDev/Citizens2/blob/2ea94aedc91d927f39ba7a70d85909d6b343a5cb/main/src/main/java/net/citizensnpcs/trait/text/Text.java#L132

If true, in terms of saving performance, could it be maybe designed the other way around ?
So, using onPlayerMovementEvent checking for nearby npcs ? Maybe with a more clever check ?
 ( assuming that you have less than 500 players which walk more than 20 blocks per second ;D )

**Comment by mcmonkey4eva** [comment] 2018-05-02 11:15
@BloodEko that would not be better. It would very likely be _worse_.

**Comment by BloodEko** [comment] 2018-05-02 11:51
Ohh, got a new idea. 
What's about an config option for the amount of checks per second ? ATM i'd be 20 as default ?
So skipping some unneeded ticks.
If you don't need it to check _very fast_ moving players.

**Comment by ryantheleach** [comment] 2018-05-03 02:39
That's pretty much what the cooldowns were designed for, just that it seems like they wern't being triggered on a failed check as well.

**Comment by BloodEko** [comment] 2018-05-03 03:02
@ryantheleach I mean a configurable cooldown for the whole task. That it may run only every second/third/... tick

**Comment by ryantheleach** [comment] 2018-05-03 04:04
https://github.com/CitizensDev/Citizens2/commit/2ea94aedc91d927f39ba7a70d85909d6b343a5cb committed a fix that might help.

**Comment by CrystallDEV** [comment] 2018-05-03 08:26
@ryantheleach what @BloodEko said makes sense. Is there a check wether a player is an npc or not? I dont think that this commit will solve anything

**Comment by mcmonkey4eva** [comment] 2018-05-03 08:33
@CrystallDEV the commit should be fairly helpful (see explanation I wrote above) and while it's not the explicit check for an NPC would be good to have (and probably also a general tickrate limit as bloodeko mentioned would help further), that commit should actually strongly help in the case of NPCs, as it will prevent the permissions check spam if an NPC is in range (by way of cooldown locking them).

**Comment by fullwall** [comment] 2018-05-03 10:41
@Kneesnap just looking at your GC options again, I noticed that you use -XX:InitiatingHeapOccupancyPercent=15 and -XX:TargetSurvivorRatio=90 

I'd be interested to see if deleting these options helped your server.

**Comment by Kneesnap** [comment] 2018-05-08 05:05
Thanks for the text fix. I'd like to suggest also doing something similar to Inventory.java too, since from what I can tell it is saving the NPC's inventory contents every tick. That could likely be reduced to once every 20 ticks if not less often.

**Comment by AIphaDragon** [comment] 2018-05-09 17:57
Kneesnap, LeaderHeads and pvparena plugins have been removed from our server and the server is no longer falls, but there are problems in the work, when there are players. 
Timings: https://timings.spigotmc.org/?url=gukamefiqe
WG report: https://pastebin.com/y505pBYR
Maybe you also have some kind of plugins interfere?

**Comment by Kneesnap** [comment] 2018-05-10 00:33
Our plugins: BungeeTabListPlus, Citizens, DungeonRealms, GlowAPI, HolographicDisplays, NoCheatPlus, NoteBlockAPI, NuVotifier, ProtocolLib, ViaVersion

**Comment by aikar** [comment] 2018-05-10 15:33
@fullwall he's using a basis of my flags (https://mcflags.emc.gs)

Removing those will definitely not help.

The main concern I see here is: -XX:G1NewSizePercent=35 -XX:G1MaxNewSizePercent=60

@Kneesnap For 6G of ram, I do not recommend setting those values

Please use 
-XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80

I provided the 35/60 suggestion for servers using larger memory sets, and I'm now even reconsidering those numbers for larger memory too. I'll be tuning my guide soon with new information (but not much changes for <= 10G flag set)

Using my recommended flags will help tremendously with your garbage collection rates.

**Comment by Kneesnap** [comment] 2018-05-10 22:34
Ah, yes. We did originally allocate 10GB when we set that up (back when we were 1.9), but we realized we didn't need that much RAM so we brought it down. I'll update our start script now.

**Comment by SlimeDog** [comment] 2018-05-16 16:04
I just stumbled upon this issue. I have a 1.12.2 (latest) test server with only 34 Citizens running across six worlds, with no players connected (it's a test server). 90+ plugins, all up-to-date with dev releases (it's a test server).

With Citizens (and Denizen and Depenizen and Sentinel) disabled, the server runs comfortably with maxheap=3G and simplified GC (-XX:+UseG1GC). In the three days since startup, only 2.7G has been allocated (so there is some small leakage elsewhere, but relatively insignificant).

With Citizens (and Denizen and Depenizen and Sentinel) enabled, maxheap is quickly fully allocated regardless of setting (between 3G and 8G tested so far), and the server crashes within two days. Testing has also been done with the Aikar-recommended GC settings, without apparent difference to the outcome.

Questions:
- How much memory should be allocated per NPC?
- How else can I contribute to isolating this issue? My test server is available, if useful.

**Comment by AIphaDragon** [comment] 2018-05-31 15:53
Kneesnap, we tested the plugin. Online: 30 people. Work time: 18 hours. Everything is stable. The problem is fixed. Try the latest version of yourself.

**Comment by mcmonkey4eva** [comment] 2018-06-28 12:52
This **should** be fixed in current builds (memleak patch from a month+ ago, and the issue-linked commits discussed above), let me know if it isn't

Inventory trait probably has room for improvement, though I'm not entirely sure offhand why it's set up the way it is or what the best way to improve it would be (without affecting whatever caused it to need resaving each tick)

**Closed by mcmonkey4eva** 2018-06-28 12:52 UTC
