### ISSUE TITLE
When NPC looks around, the animation is smoother

### ISSUE THREAD

**Issue by luoxiawuchen** [CitizensDev/Citizens2#2790] opened 2022-04-18 13:34 UTC
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

When I use /NPC lookclose -- randomlook true to turn on random looking around, NPC rotation is completed in an instant, rather than a smooth animation transition. The larger the random rotation range is set, the more obvious this "jamming" is

Or it can be described in this way. When NPC looks around at random, their body rotates too fast, which seems strange

I think this video presentation can illustrate this more intuitively：
![image](https://user-images.githubusercontent.com/64759847/163815703-37bb5010-a867-44f1-b472-8517d8c27a23.png)
https://app.tmp.link/index.html?tmpui_page=/file&ukey=625d68154ac54

I hope it can make NPC's animation smoother when looking around. I think it will be more natural

**Comment by mcmonkey4eva** [comment] 2022-04-23 08:10
The commit https://github.com/CitizensDev/Citizens2/commit/f358f6fb2ecd544125a24441d6dbbd7d720062f3 is initial work towards this (but not actually implementing proper smoothness yet, presumably a followup commit will actually implement it all the way)

**Comment by mcmonkey4eva** [comment] 2022-04-23 08:30
Actually also, I believe this is essentially a duplicate of #2247 ? Albeit a more detailed one

**Comment by BigMeowcatsunny** [comment] 2022-05-15 21:51
i would use /npc look

**Closed** 2022-12-11 11:31 UTC
Labels: Feature Request
