### ISSUE TITLE
Non-player NPCs are randomly dissapearing.

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#674] opened 2016-03-10 18:00 UTC
On minecraft 1.9 using the latest #1325 devbuild, my villagers from my mall are randomly dissapearing frequently. The player npc's are never dissapearing. /citizens reload spawns them back.

This might occur on a server restart or when no one is in the mall, I think.

Also when I delete a villager, it comes back after a restart.

**Comment by fullwall** [comment] 2016-03-11 16:05
Plugin list? Are you using BungeeCord?

**Comment by Sikatsu** [comment] 2016-03-11 18:17
Spigot 1 version behind. I shared the plugin list on an closed issue
earlier I believe, otherwise I can send it later.

Op vr 11 mrt. 2016 17:06 schreef fullwall <notifications@github.com>:

**Comment by leasoncre** [comment] 2016-03-12 01:14
might be related to #660

**Comment by Sikatsu** [comment] 2016-03-12 08:31
Not really, when I use /citizens reload all my npc's are back. But the villagers from my mall keep vanishing :s 

Plugin list: http://prntscr.com/ae807y

**Comment by fullwall** [comment] 2016-03-16 09:17
If you set keep-chunks-loaded to true in the config, do they still disappear?

**Comment by Sikatsu** [comment] 2016-03-16 15:26
They still dissappear. Only the non-player NPCs tho, for me I only use ''Villagers'' which are vanishing.

**Comment by fullwall** [comment] 2016-03-16 15:31
OK, looking into it.

**Comment by Sikatsu** [comment] 2016-03-18 17:30
@fullwall It happens atleast 3 times a day that I need to use /citizens reload because my villagers disappear.

**Comment by mcmonkey4eva** [comment] 2016-03-18 23:48
Can you test with clearlag removed?

**Comment by Sikatsu** [comment] 2016-03-19 06:35
Even without clearlag it is still dissapearing, it seems to happen when a chunk gets unloaded.

**Comment by fullwall** [comment] 2016-06-12 15:53
Closed as duplicate of https://github.com/CitizensDev/Citizens2/issues/803

**Closed by fullwall** 2016-06-12 15:53 UTC
Labels: Bug Report
