### ISSUE TITLE
NPC's Disappearing

### ISSUE THREAD

**Issue by RocketManKian** [CitizensDev/Citizens2#2634] opened 2021-08-13 23:03 UTC
The output of command `/version` on my server is: **(PLEASE FILL IN)**[23:00:51 INFO]: This server is running Paper version git-Paper-176 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8083670)
Previous version: git-Paper-154 (MC: 1.17.1)
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**>> = [23:01:45 INFO]: Citizens version 2.0.28-SNAPSHOT (build 2357)

Description: For some weird reason my NPC's keep getting removed for no apparent reason. The first time this happened I managed to recover them by renaming one of the 3 Save files present within the folder. But this time it has been completely deleted. I am doing nothing specific whatsoever, but it seems to happen after Server Restarts.

**Comment by mcmonkey4eva** [comment] 2021-08-14 00:00
Please [Pastebin](https://paste.denizenscript.com/new/Log) your server [logs](https://wiki.citizensnpcs.co/Logs).

**Comment by RocketManKian** [comment] 2021-08-14 00:23
https://paste.denizenscript.com/View/87356

**Comment by RocketManKian** [comment] 2021-08-14 00:23
https://pastebin.com/DJ2Xxr0U

**Comment by mcmonkey4eva** [comment] 2021-08-14 00:43
- Your Citizens version is slightly behind, and some recent commits are potentially relevant, so step 1 is update: https://ci.citizensnpcs.co/job/Citizens2/
- You have a variety of data packs, which generally aren't well supported on Spigot, including at least one error message seemingly caused by them
- you have errors from `TAB` and `InteractiveChatDiscordSrvAddon`
- you are running `CitizensText`, a third-party addon that doesn't seem to be well-implemented and regardless doesn't need to exist, as `/npc text` is a built-in feature.
- `NPC_Destinations` appears to be actively intentionally messing with Citizens saves file
- You're running `Spartan`, an anticheat - anticheats can sometimes mistake NPCs for players and break stuff as a result. Test for [Plugin Conflicts](https://wiki.citizensnpcs.co/Plugin_Conflict).

**Comment by MODNMETL** [comment] 2021-08-17 11:36
>     * `NPC_Destinations` appears to be actively intentionally messing with Citizens saves file

Could you elaborate on the issue with NPC Destinations? We upgraded NPCDestinations to 2.6.0 version in July and we lost all our NPCs from the Citizens plugin.

**Comment by Nutty101** [comment] 2021-08-17 14:23
You can close this one on the Citizens side. Working with them on the issue

**Closed** 2021-09-05 06:37 UTC
Labels: Waiting For Reply
