### ISSUE TITLE
Summon command summons pig when invalid entity is entered

### ISSUE THREAD

**Issue by TrollyLoki** [CitizensDev/Citizens2#2004] opened 2019-12-22 16:33 UTC
When Citizens on 1.15.1 is loaded the vanilla /summon command summons a pig instead of erroring when an entity name that doesn't exist is entered.

The output of command `/version` on my server is: **CraftBukkit version git-Spigot-2ee05fe-2d9db47 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1799)**

Log: https://pastebin.com/tSAvrwp5
Config: https://pastebin.com/PnihFeD4

**Comment by mcmonkey4eva** [comment] 2019-12-22 19:10
... have you tried on the same server, minus Citizens? That seems rather odd to have been caused by Citizens.

**Comment by TrollyLoki** [comment] 2019-12-22 19:26
Yes it does seem to be strange that it is caused by Citizens, but I did try removing it from the same server and after I restarted it the problem was gone

**Comment by mcmonkey4eva** [comment] 2019-12-22 22:47
Replicated.

It's likely because this method: https://github.com/CitizensDev/Citizens2/blob/3e48abeebbdafc390c8bf138137a4cbe5c0f4656/v1_15_R1/src/main/java/net/citizensnpcs/nms/v1_15_R1/util/CustomEntityRegistry.java#L77-L82
is incorrectly implemented for 1.15 (and possibly other versions)

The final line should `return this.wrapped.getOptional(var0);`
Otherwise it produces inconsistent behavior (as `RegisryBlocks#get` is implemented in such a way that it never returns null, instead it returns a default - in this case, `Pig`).

**Comment by mcmonkey4eva** [comment] 2019-12-23 02:13
Fixed by https://github.com/CitizensDev/Citizens2/commit/1a0282d970f5db8af55054854c7f0ff4e804574e in build 1801+ from https://ci.citizensnpcs.co/job/Citizens2/

**Closed by mcmonkey4eva** 2019-12-23 02:13 UTC
Labels: Bug Report, Special, Work To Do
