### ISSUE TITLE
Command NPC ClassCastException

### ISSUE THREAD

**Issue by EmberCM** [CitizensDev/Citizens2#2120] opened 2020-04-22 18:28 UTC
Stacktrace error when right clicking an NPC with command
https://i.ember.zone/WcLmCbjBY9Anfr3n.png
https://hastebin.com/ewilihutag.py

The output of command `/version` on my server is: CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.26-SNAPSHOT (build 1861)

**Comment by mcmonkey4eva** [comment] 2020-04-22 19:44
Duplicate of #2114

**Closed by mcmonkey4eva** 2020-04-22 19:44 UTC
