### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Diddyer** [CitizensDev/Citizens2#212] opened 2015-01-23 15:52 UTC
writhe npc create name

crash server

no deleted this post, please, srr for my bad english

VERSION SERVER:
This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

VERSION CITIZENS:
Citizens v2.0.13-SNAPSHOT (build 1166)

Log:
http://pastebin.com/T5YDrXA8

Error:

[10:16:51] [Server thread/INFO]: Diddyer issued server command: /npc create Test

[10:16:52] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_7_R4.ReportedException: Ticking entity
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:717) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.(Ljava/lang/String;ZI)V
at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277) ~[?:?]
at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150) ~[?:?]
at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
... 4 more
[10:16:52] [Server thread/ERROR]: Cause of unexpected exception was
java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.(Ljava/lang/String;ZI)V
at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277) ~[?:?]
at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150) ~[?:?]
at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [custom.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[10:16:52] [Server thread/ERROR]: This crash report has been saved to: /home/Minejoin/multicraft/servers/XXXXX/./crash-reports/crash-2015-01-23_10.16.52-server.txt
[10:16:52] [Server thread/INFO]: Stopping server[/CODE]

**Comment by mcmonkey4eva** [comment] 2015-01-23 20:35
Duplicate of your /own post/

**Closed by mcmonkey4eva** 2015-01-23 20:35 UTC
