### ISSUE TITLE
NPC name aren't reset

### ISSUE THREAD

**Issue by LinearBotSystems** [CitizensDev/Citizens2#1253] opened 2017-07-28 16:04 UTC
Spigot 1.12, Citizen 2.0.22, Sentinel 1.3.1

I have an NPC which has a strange name problem after I created him he suddenly had the name of a generic soldier type which I created "Soldier of the Expedition Force" instead of "Captain of the Expedition Force" 

I tried to rename him into Captain Carrot to change it after wards back this was the result:

![2017-07-28](https://user-images.githubusercontent.com/25264743/28725721-a3174fda-73be-11e7-8edb-29fb2f7f052f.png)
![2017-07-28 1](https://user-images.githubusercontent.com/25264743/28725726-a4d8306e-73be-11e7-804f-902d23b1a0aa.png)

My saves:
https://pastebin.com/HtY2knn8

**Comment by LinearBotSystems** [comment] 2017-07-31 20:08
Some small update to this I did rename him again but his name only stayed for a short time after this he is again only "Soldier"

**Comment by mcmonkey4eva** [comment] 2017-07-31 22:15
The lead dev doesn't check this issues page very often, he's been busy :/

**Comment by LinearBotSystems** [comment] 2017-08-05 10:07
Which is very unfortunate, anyway it is like I thought the name wandered to another NPC  there must be an index error in the loop which gives the name plates when loading the settings. It looks like the function is very broken /:

**Comment by fullwall** [comment] 2017-08-22 12:46
Hmmm...  if you delete the Soldier of the Expedition Force is this resolved?

**Comment by fullwall** [comment] 2018-03-15 07:58
Assuming this is a scoreboard issue - there's a lot of dupes of this so closing this one.

**Closed by fullwall** 2018-03-15 07:58 UTC

**Comment by LinearBotSystems** [comment] 2018-05-29 09:18
What scoreboard ?

**Comment by mcmonkey4eva** [comment] 2018-05-29 09:22
The scoreboard is the system in minecraft that powers longer-than-16 character names. Long names that screw up are generally caused by scoreboard conflicts (if two NPCs have the same 16 character base names, the scoreboard extension will pick one name for both of them)
