### ISSUE TITLE
npc won't look at player when someone walk around te npc

### ISSUE THREAD

**Issue by herotechnl** [CitizensDev/Citizens2#2526] opened 2021-04-08 20:40 UTC
The output of command `/version` on my server is: **(1.16.5)**
The output of command `/version citizens` on my server is: **(2.0.27)**
![2021-04-08_22 27 59](https://user-images.githubusercontent.com/37268243/114092237-f0b99d00-98b9-11eb-8a0f-c516b67803b7.png)

Dear CitizensDevs,

So i have a server where i use citizens and dtl trader for a shop. 4 day's ago i updated citizens and now my npc won't look at players. every command to let it look isn't working. so have anyone a idea what i can do. 

https://user-images.githubusercontent.com/37268243/114092950-c87e6e00-98ba-11eb-843c-db675bca5c36.mp4

Best regards,
    Hero

**Comment by mcmonkey4eva** [comment] 2021-04-08 21:03
Duplicate of #2524 

This was already fixed, update: https://ci.citizensnpcs.co/job/Citizens2/

**Closed by mcmonkey4eva** 2021-04-08 21:03 UTC
