### ISSUE TITLE
1.14.1 console error

### ISSUE THREAD

**Issue by successed** [CitizensDev/Citizens2#1794] opened 2019-05-25 13:23 UTC
[16:21:19] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.25-SNAPSHOT (build 1689)
[16:21:19] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.25-SNAPSHOT (build 1689) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/EntityLLamaTrader
	at net.citizensnpcs.nms.v1_14_R1.util.CustomEntityRegistry.<clinit>(CustomEntityRegistry.java:184) ~[?:?]
	at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.<clinit>(NMSImpl.java:1695) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_212]
	at net.citizensnpcs.util.NMS.loadBridge(NMS.java:254) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.1.jar:git-Paper-42]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.1.jar:git-Paper-42]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.1.jar:git-Paper-42]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-42]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.1.jar:git-Paper-42]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.EntityLLamaTrader
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.14.1.jar:git-Paper-42]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.1.jar:git-Paper-42]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 15 more
[16:21:19] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.25-SNAPSHOT (build 1689)

**Comment by mergu** [comment] 2019-05-25 14:06
Duplicate of https://github.com/CitizensDev/Citizens2/issues/1781, update to 1.14.1

**Comment by mcmonkey4eva** [comment] 2019-05-25 20:05
That's actually, hilariously, not a duplicate issue. It's the inverse issue. Note the `LLama` instead of `Llama`. Yes literally the capital vs lowercase `L`. One of the more incredible breaking version changes.

@successed update to latest Citizens dev build for compat with 1.14.1: https://ci.citizensnpcs.co/job/Citizens2/

**Closed by mcmonkey4eva** 2019-05-25 20:05 UTC

**Comment by successed** [comment] 2019-05-25 20:06
i have latest t,y.
