### ISSUE TITLE
Skins not showing

### ISSUE THREAD

**Issue by ElectroSpy** [CitizensDev/Citizens2#473] opened 2015-08-02 22:40 UTC
So when i create NPC with /npc create "name", he don't have it (default (random) steve/alex skin). Even if i try /npc skin "name". I'm using bungee (online mode). No error in console. Build #1251

**Comment by logicalPolaris** [comment] 2015-08-03 18:30
Duplicate of #468 .

**Closed** 2015-08-10 08:29 UTC
