### ISSUE TITLE
1.19.2 errors on boot

### ISSUE THREAD

**Issue by stijnb1234** [CitizensDev/Citizens2#2850] opened 2022-08-08 08:07 UTC
### `/version` output

```txt
[10:05:38 INFO]: Checking version, please wait...
[10:05:39 INFO]: This server is running Paper version git-Paper-116 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a47301e)
You are running the latest version
Previous version: git-Paper-113 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
[10:05:47 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2663)
[10:05:47 INFO]: Website: http://www.citizensnpcs.co
[10:05:47 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/99928

### config.yml

https://paste.denizenscript.com/View/99929

### saves.yml

https://paste.denizenscript.com/View/99930

### Description

When I boot my server, I get some NBT exceptions in my console. Only two of my NPCs won't spawn correctly.

**Comment by aXe18** [comment] 2022-08-08 09:45
I have same issue

**Comment by mcmonkey4eva** [comment] 2022-08-08 09:56
That's either
A: something broken in Paper/spigot internals, or
B: something wrong in the copy of player head metadata on items


------

Quick issue detail grab:

```

[Citizens] An exception occurred while the trait inventory was spawning for NPC ID 333.
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.c()"
   because the return value of "java.util.Map$Entry.getValue()" is null
at net.minecraft.nbt.NBTTagCompound.g(NBTTagCompound.java:458)
at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:685)
at net.minecraft.world.item.ItemStack.o(ItemStack.java:676)
at net.minecraft.network.protocol.game.PacketPlayOutSetSlot.<init>(PacketPlayOutSetSlot.java:19)
at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113)
at Citizens-2.0.30-b2663.jar//net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:214)
at Citizens-2.0.30-b2663.jar//net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:96)
at Citizens-2.0.30-b2663.jar//net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:297)
```

For two NPCs, each of which have item data similar to:
```yml

      equipment:
        hand:
          type_key: player_head
          amount: 1
          meta:
            repaircost: 0
            skull:
              texture: ewogICJ0aW1lc3RhbXAiIDogMTYyNTM4OTM2NDM1NiwKICAicHJvZmlsZUlkIiA6ICI4MjlmZjZjN2FmMzE0NWZhYTc5NTcwZGJlOWVmZTlhYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfcHJlc2VudCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yNGVhM2YwNWNmYTQyZGRmMjU5ZTE0YTQzYzBjNDdmZjNlMjM2MmZhMzI0NTZkOGE1MDFjOWQ1NTdhNmY5YzIwIgogICAgfQogIH0KfQ==
              uuid: 829ff6c7-af31-45fa-a795-70dbe9efe9ab
              properties:
                textures:
                  '0':
                    name: textures
                    value: ewogICJ0aW1lc3RhbXAiIDogMTYyNTM4OTM2NDM1NiwKICAicHJvZmlsZUlkIiA6ICI4MjlmZjZjN2FmMzE0NWZhYTc5NTcwZGJlOWVmZTlhYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfcHJlc2VudCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yNGVhM2YwNWNmYTQyZGRmMjU5ZTE0YTQzYzBjNDdmZjNlMjM2MmZhMzI0NTZkOGE1MDFjOWQ1NTdhNmY5YzIwIgogICAgfQogIH0KfQ==
                    signature: aE0ntTNZYZAYfPhrSC4pPGcgJn9tBRvBEIAmIaILhiPMKbRZtSlYitnvIqAi3U8bbwxQyJ92DbT0yjqpb0HVRRC9D7/Tw9FuUGl8fNMcas3HmxX0MJDcT0Th1vnVQmTqr1xJeJTrU0YLaBkTgr3uU9+F1rMsFXAOd9rUIfkJzY6Vt2i6UYpGT5dOVu7dqxaljzJnBDOPx+KYtnzM+o1+SP1w42V/WDu5+wkK3BT1zssRqepeXZ5H77FVVnY6f8koIKZ40ydlV39uvDG7glpecKqt5aj9dw8xZMX/y0IJuzqEIUBczq4MuyTkDjH5NLvsYP/T+M5YxEV/jn7ZsPDbnGKP+56DeyxNpDDN9toYvH0oAgRiDtT00EjTRxFKonCFXoLIPwhQ+aaGLB7T4NLHqvc5kJzH8BI34QgvKBNOq5E8j9Jo7Ssv2DwUGjBYr8NFk9Iwm6bRAyq7winTg6Bk3v2tz0dsUCuxz7wCW0IRwQQIn2EYnl24HoXQ+5RhEXkrR1TyTQaih3933palCqpQMH/xRyBtl5E+fdgSJfeP2Syrbvsk9P4fZa3sqK68YGrjFoF9T3D+HE2GtUG6GaQc29SXjVQlJN2iJ1eChxJb/46Gzn1v+9cBFChoc9AoWJpi017vGZVdDZ7CivNF24Y8ZBG5RK+u4vHRFoiKhnp8owI=
              owner: MHF_present
(...)
      inventory:
        '0':
          type_key: player_head
          amount: 1
          meta:
            repaircost: 0
            skull:
              texture: ''
              owner: MHF_present
```

Note that the 'equipment' copy is set correctly (albeit duplicated), and the 'inventory' copy has the owner data but hasn't loaded the texture

**Comment by stijnb1234** [comment] 2022-08-08 10:01
Possibly caused by the spigot remapping maven plugin.

Found these (old) issues:
https://hub.spigotmc.org/jira/browse/SPIGOT-6647
https://hub.spigotmc.org/jira/browse/SPIGOT-6550

**Comment by ScuroK** [comment] 2022-10-11 17:06
Im using paper 1.19.2 and some of my NPCs dont spawn too. I even created an NPC of the same type and it disappeared afrer restart. Other NPCs of the same type are just fine. It seems totaly random.

**Comment by Justugh** [comment] 2022-12-26 03:21
Can confirm this is happening for me as well, running latest Citizens version as well as latest Paper version (1.19.3). Any update on this?

**Comment by fullwall** [comment] 2022-12-26 04:55
@Justugh can you post a log and saves.yml entry then?

**Comment by Justugh** [comment] 2022-12-26 05:10
Already modified my saves.yml to mitigate the issue however it was due to NPCs holding a player head item with a custom texture.

In reference to what was stated before, I can confirm the player head items were valid and had no issues.
```[21:55:59] [Server thread/ERROR]: [Citizens] An exception occurred while the trait inventory was spawning for NPC ID 10.
[21:55:59] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
[21:55:59] [Server thread/WARN]: 	at net.minecraft.nbt.NBTTagCompound.h(NBTTagCompound.java:471)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:693)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.o(ItemStack.java:684)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayOutSetSlot.<init>(PacketPlayOutSetSlot.java:19)
[21:55:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:218)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:97)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:349)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:313)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:394)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.EventListen.spawn(EventListen.java:742)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:717)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.EventListen.access$000(EventListen.java:117)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.EventListen$2.run(EventListen.java:187)
[21:55:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[21:55:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[21:55:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[21:55:59] [Server thread/ERROR]: [Citizens] An exception occurred while the trait inventory was spawning for NPC ID 9.
[21:55:59] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
[21:55:59] [Server thread/WARN]: 	at net.minecraft.nbt.NBTTagCompound.h(NBTTagCompound.java:471)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:693)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.o(ItemStack.java:684)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayOutSetSlot.<init>(PacketPlayOutSetSlot.java:19)
[21:55:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:218)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:97)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:349)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:313)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:394)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.EventListen.spawn(EventListen.java:742)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:717)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.EventListen.access$000(EventListen.java:117)
[21:55:59] [Server thread/WARN]: 	at Citizens-2.0.30-b2845.jar//net.citizensnpcs.EventListen$2.run(EventListen.java:187)
[21:55:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[21:55:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[21:55:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[21:55:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)```

**Comment by fullwall** [comment] 2022-12-27 05:07
Fixed on new builds.

**Closed by fullwall** 2022-12-27 05:07 UTC
Labels: Bug Report
