### ISSUE TITLE
All Player Type NPCs disappeared!!!

### ISSUE THREAD

**Issue by HexonCz** [CitizensDev/Citizens2#2115] opened 2020-04-20 17:35 UTC
I am running The Paper Spigot server and all previously created and functional Player type NPCs are now  invisible/don't spawn... (they are in NPCs list but they are not visible and usable....) When I try to spawn new i is also invisible or IDK how to describe it...
latest.log: **https://pastebin.com/eg2kGk6W**
PaperSpigot version:**git-Paper-199 (MC: 1.15.2)**
Citizens version: **2.0.26-SNAPSHOT (build 1886)**

**Comment by calico-kid** [comment] 2020-04-20 17:40
Update to 200 or above

**Comment by calico-kid** [comment] 2020-04-20 17:41
Which in the future should be the first thing ya do to barony things haven’t been fixed already :)

**Comment by JRKPirna** [comment] 2020-04-20 20:07
This also happens to us, we already tried various plugin versions including the latest as well as beta ones

**Comment by mergu** [comment] 2020-04-20 20:18
Use the latest version of Paper/Spigot and the latest version of Citizens, and if it's still not loading post a full latest.log please

**Comment by mcmonkey4eva** [comment] 2020-04-21 02:55
Duplicate of #2113

**Closed** 2020-04-21 02:54 UTC
