### ISSUE TITLE
Inconsistent player validity checking in lookclose trait

### ISSUE THREAD

**Issue by elgbar** [CitizensDev/Citizens2#2440] opened 2021-01-20 01:01 UTC
When using the trait `lookclose` what "close" actually means is defined in two different ways. First when looking if there are any players nearby i.e. in the `findNewTarget()` method and secondly if the target still is close i.e. `hasInvalidTarget()`.

In the first method players are looked for within a AABB of size `range`. In other words a cube with the radius of `range` is centred at the npcs location and all players within it are added as the potential new target. This is a perfectly valid way of checking for nearby players. 

However the trouble begins when we are checking if the player is still within a valid range. To do this the method `hasInvalidTarget()` checks if the DISTANCE between the npc and player are less than `range`. 

This is not the same as checking if a player is within a AABB with size `range`! As of now what will happen if the player stands `range` block diagonally away from the npc is that the `hasInvalidTarget()` will invalidate the current target player then call `findNewTarget()` and potentially find the same player again.

So it seems that in a sense the AABB method wins the battle as a cube is larger than a sphere of the same radius. It seems there are two solutions to this problem. Either only use the AABB method or use the distance method.

The output of command `/version` on my server is: `This server is running Paper version git-Paper-436 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
The output of command `/version citizens` on my server is: `Citizens version 2.0.27-SNAPSHOT (build 2226)`

**Comment by mcmonkey4eva** [comment] 2021-01-20 01:06
While what you said all seems to check out as technically correct, I think you've forgotten to include, er... what the issue is?
What problem arises from this slight internal inconsistency?

**Comment by elgbar** [comment] 2021-01-20 01:23
> While what you said all seems to check out as technically correct, I think you've forgotten to include, er... what the issue is?
> What problem arises from this slight internal inconsistency?

Fixing this improves the performance of the plugin (`findNewTarget` is called every tick). I found out about this issue while trying to fire an event when the look target changes. I noticed that the event would fire twice every tick, so I submitted a bug report.

If you'd like I can create a pr to fix this, #2441, and add a `NPCLookCloseChangeTarget` event.

**Comment by elgbar** [comment] 2021-01-20 08:40
For completeness sake, I'll post the content of issue #2441

When using the trait `lookclose` what factors determine if a player is valid is not consistent between finding and invalidating players. See the table below to see the differences. An `X` marks it as checked.

| Test                              | findNewTarget | hasInvalidTarget | Note                                                                                            |
| :-------------------------------- | :-----------: | :--------------: | :---------------------------------------------------------------------------------------------- |
| If entity is a NPC                |       X       |                  | This should not be checked in invalidate, included for completeness                             |
| Same world                        |       X       |        X         |                                                                                                 |
| Players gamemode is not spectator |       X       |                  |                                                                                                 |
| Player has INVISIBILITY potion    |       X       |                  |                                                                                                 |
| Player is vanished via plugin     |       X       |                  |                                                                                                 |
| Distance between player and NPC   |       X       |        X         | Both check, but in different ways. See original description above                               |
| Player is online                  |               |        X         | Player will be online when retrieved via an AABB call, so no real need when finding new targets |
| Player is valid                   |               |                  | Should be done in `hasInvalidTarget` to prevent npc not looking at a stale player object        |

As can be seen the npc will turn to look at a vanished/spectator/invisible player if they become so while being the target the NPC.

**Comment by mcmonkey4eva** [comment] 2021-01-20 09:42
fullwall committed https://github.com/CitizensDev/Citizens2/commit/58443ee72682742bea46988c2c23ef8574e3210c which seems to resolve this issue to make both methods fully consistent with each other.

**Closed by mcmonkey4eva** 2021-01-20 09:42 UTC
Labels: Bug Report, Work To Do

**Comment by elgbar** [comment] 2021-01-20 10:18
Alright, thanks for the quick fix.
