### ISSUE TITLE
Npc's lose their commands

### ISSUE THREAD

**Issue by MetooMango** [CitizensDev/Citizens2#2493] opened 2021-02-24 20:29 UTC
NPCS lose their commands for no reason what so ever. Whenever I add it, it works for a few seconds and then it stops. Considering I payed for premium I would not expect a premium plugin to behave like this! I need a fix asap! I would give u a log of the console but I already checked it and there is nothing on it If you want a log tell me and ill send it
![image](https://user-images.githubusercontent.com/78914989/109061281-612ba680-76de-11eb-9a9e-2b6572ce91c5.png)
![image](https://user-images.githubusercontent.com/78914989/109061410-8a4c3700-76de-11eb-8053-26abb628afbb.png)

Citizens Config: https://pastebin.com/4BMYL1tM

The output of command `/version` on my server is: git-Paper-468
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT

**Comment by bluelhf** [comment] 2021-02-24 20:35
Possibly a duplicate of #2494

**Comment by MetooMango** [comment] 2021-02-24 20:36
how do i fix

**Comment by bluelhf** [comment] 2021-02-24 20:45
@MetooMango [Update Citizens](https://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/artifact/dist/target/*zip*/target.zip)

**Comment by mcmonkey4eva** [comment] 2021-02-25 13:41
The link to update is https://ci.citizensnpcs.co/job/Citizens2/ not, er, whatever that link was. (Just click the giant `Citizens-2.0.27-b2272.jar` link on that page).
But, yeah, already-fixed bug, just update.

**Closed by mcmonkey4eva** 2021-02-25 13:41 UTC
