### ISSUE TITLE
New NPCs not saving on 1.16.1

### ISSUE THREAD

**Issue by DrakePork** [CitizensDev/Citizens2#2235] opened 2020-07-10 00:58 UTC
After creating an NPC on 1.16.1 and then restarting the server it goes away and gives this error [Pastebin](https://pastebin.com/0VyPJ3fG).

I also tried using the /citizens save command, however that threw a nullpointerexception warning. [Pastebin](https://pastebin.com/WYvQzJZR)

But yeah NPCs doesnt get saved into memory so they do not exist after a server restart.

The output of command `/version` on my server is: **git-Paper-84 (MC: 1.16.1)**
The output of command `/version citizens` on my server is: **Citizens v2.0.27-SNAPSHOT (build 2044)**

**Comment by mcmonkey4eva** [comment] 2020-07-10 01:11
This is a known issue caused by a problem within Spigot, not within Citizens.

An attempted workaround was added via https://github.com/CitizensDev/CitizensAPI/commit/80320eb274da3573c5274e3c4c5e0aa0cc33065a which catches the error and display it but then allows it to save anyway.
... Unfortunately, it seems that just printing an error report inadvertently triggers the same underlying Spigot API method that the error is within... meaning trying to display the error causes the error to happen again.

**Comment by mcmonkey4eva** [comment] 2020-07-10 01:25
Should be fixed by https://github.com/CitizensDev/CitizensAPI/commit/6ee5c65900b980237b9df8c22591a12cf2f667bf for build 2045+ from https://ci.citizensnpcs.co/job/Citizens2/

**Closed by mcmonkey4eva** 2020-07-10 01:25 UTC
Labels: Confirmed Bug, Work To Do
