### ISSUE TITLE
Citizens PlayerUpdateTask CPU Usage

### ISSUE THREAD

**Issue by oloflarsson** [CitizensDev/Citizens2#801] opened 2016-05-23 08:48 UTC
The `net.citizensnpcs.util.PlayerUpdateTask` is currently the top timing on my server network. It consumes ~3.48% of the main thread CPU. I was wondering if you had any ideas for how to performance optimize this task?

**MassiveLag Timings List:** https://gyazo.com/a473726bef32c5b8efa8af00e8aefb28
**MassiveLag Timings Show:** https://gyazo.com/fb0f158fa81f97b6987180bcf2bd70e4

**Comment by mcmonkey4eva** [comment] 2016-05-24 00:40
Do you have a lot of NPCs, or NPCs performing complex action?

That task does basically all the calculations for every player-type NPC spawned.

**Comment by fullwall** [comment] 2016-05-27 05:12
This is a duplicate of https://github.com/CitizensDev/Citizens2/issues/724 - as I said in that issue, I'd really love to see a profiler screenshot with inherent method times instead of cumulative % or 'timings'

**Comment by Koudja** [comment] 2016-06-27 17:36
Hello, since an upgrade from 1.9.4 to 1.10.2 (spigot) my server encounter similar issue. Here is a warmroast,
https://framapic.org/Iym70xOlVQqt/UHfIVmkaP0jj.png

I have been digging a bit and figured that Citizens worked by calling every tick 'World.g(Entity)' which is basically adding a new entity to a world : is that normal ?

**Comment by fullwall** [comment] 2016-06-29 05:44
@Koudja world.g is actually tickEntity

**Comment by Koudja** [comment] 2016-07-01 08:58
#839 #813 seems to be same issue (must be hard for you to track this :D ).

I noticed that this problems is not always there. I suspect that one or some NPCs are at fault. On my server, with same amount of player, sometimes we are at 20 TPS and sometimes at 9 (and only Citizens causing it). Also, when it happens TPS do not fall down at once but decrease gradually.

As a temporary dirty fix, I built Citizens by commenting "tickPotionEffects" (reported taking 13%) from NPC tick function. We also cleaned half of our NPC (we had initially 624 NPCs, now down to 320). (And thanks to that, I cannot reproduce this problem anymore, so I am still waiting for an another warmroast, sorry)

It might be interesting to say that this problem arised when moving to spigot 1.10.2 where we also removed Sentry in favor of Sentinel (that might had an impact somehow).

**Comment by mcmonkey4eva** [comment] 2016-07-01 12:40
@Koudja If anything, the last line should have the opposite effect. One of the reasons we dropped Sentry was because of overly common undiagnosable lag issues. Sentinel shouldn't be doing that - and if it does do that for some reason in the future, it has its own special tick code and all, so it would show up visibly on its own and can be better dealt with. In theory, at least. (Though potentially within the Citizens tick structure).

Also, why was tickPotionEffects so slow? Do you commonly have potion effects applied to NPCs?

And more generalized, what are your various NPCs doing (600+ is a lot of NPCs) - if they're EG all walking paths or are all configured as combat NPCs, they may simply be doing too many things at once. Though from your first line it sounds like a small number of bad NPCs rather than having too many in general.

It may be difficult, but it may be beneficial to attempt to track down exactly which NPCs are at fault, and figure out what they're doing. This'd be accomplished probably by simply flying from NPC to NPC, making sure it's active, and watching the TPS while you interact with it.

I had a similar problem on my old server with Sentry, and ended up managing to track it down to two town guards in one particular location, and removing them sufficed as a workaround.
If I had that problem more recently, I probably would have been able to get more detailed lag information and help figure out what was wrong. Every bit of information gathered after finding them could help - what they're doing, what the profiler shows when only those NPCs are loaded, how they act when moved elsewhere, etc.

**Comment by fullwall** [comment] 2016-07-02 17:19
Should be a little better in the latest build - the potion effects were being sent too often.

**Comment by Koudja** [comment] 2016-07-03 07:59
@fullwall Hello, thanks for this update. This is a small message to say that I am still waiting for logs (no problem since  4 days). I removed my custom built version and took latest one.

@mcmonkey4eva Thanks for clearing out Sentinel, as for our NPCs, I would say 70% were not moving with few being sentinel-ized but we still had 100+ NPCs moving (following a fixed path: guards doing patrols). None of our NPCs are subject of potions, I do not understand either why "tickPotionsEffects" take(took?) so much.
If problem happens today, I will add some debug to Citizens and report a more detailled finding on which NPCs is taking longer than usual and hopefully why.

Thanks for helping us on that matter !

**Comment by fullwall** [comment] 2016-07-03 08:29
@koudja - it took a lot because the updated packets were being sent by Minecraft every tick which can be CPU intensive

**Comment by Koudja** [comment] 2016-07-22 17:51
No problems to report after 19 days, so I think this one could be closed. Thanks !

**Closed** 2016-07-22 23:17 UTC
