### ISSUE TITLE
disconnecting with Invalid move player packet received on teleport.

### ISSUE THREAD

**Issue by PaintsplattersMC** [CitizensDev/Citizens2#2847] opened 2022-08-05 23:53 UTC
### `/version` output

```txt
[18:45:21 INFO]: This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
```

### `/version Citizens` output

```txt
[18:45:35 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2640)
[18:45:35 INFO]: Website: http://www.citizensnpcs.co
[18:45:35 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/99828

### config.yml

https://paste.denizenscript.com/View/99829

### saves.yml

https://paste.denizenscript.com/View/99830

### Description

1: Download and set up a Paper 1.19-81  server. leave all configs default.

2: Install plugins: EssentialsX Core, Citizens 2640 and denizen 1774 rel.

3: Create an NPC with any name. "/npc create test"

4: Run command "/tp 1000 100 1000"

5: Client disconnects with error " Invalid move player packet received"

Other notes: This error does not occur when both citizens and denizen are not enabled at the same time.

Here is the issue on paper github:  https://github.com/PaperMC/Paper/issues/8222

**Comment by PaintsplattersMC** [comment] 2022-08-05 23:57
Even if this issue is not specific to denizen and citizens hopefully this issue can be resolved.

**Comment by mcmonkey4eva** [comment] 2022-08-06 01:01
Duplicate of #2836  - not likely to be Citizens directly at fault as noted in the Paper issue where servers not running Citizens also have the issue

**Closed by mcmonkey4eva** 2022-08-06 01:01 UTC

**Comment by PaintsplattersMC** [comment] 2022-08-06 02:51
as per my comment in #2836 the plugins that cause this issue may share some problem in common.

**Comment by ilfarpro** [comment] 2022-10-16 19:29
My players Constantly getting kicked from server:
```
[21:50:53 INFO]: Titanik_777 issued server command: /spawn
[21:50:56 INFO]: Titanik_777 lost connection: Invalid move player packet received
[21:50:56 INFO]: [voicechat] Disconnecting client Titanik_777
[21:50:56 INFO]: Titanik_777 покинул(а) игру
[21:50:56 WARN]: Disconnected on accept teleport packet. Was not expecting position data from client at this time
```
This only happens on teleport. 
Please provide me information, how can I verbose this error, gather more Information. I'm ready to collect data and investigate this. But don't know how. 
This issue driving me crazy, I already blamed my plugins, then realized it wasn't caused by them....
