### ISSUE TITLE
npc dissapear after a restart when using /npc name

### ISSUE THREAD

**Issue by ImHumbug** [CitizensDev/Citizens2#1590] opened 2018-10-12 19:59 UTC
Spigot version: 1.13.1-R0.1 SNAPSHOT
Citizen version: 2.0.24-SNAPSHOT (build 1581)
NPC with name toggle off don't spawn after a restart. The fix is to write /citizens reload.
I'm not getting a error in the console.

**Comment by mcmonkey4eva** [comment] 2018-10-12 20:02
Is this equivalent to https://github.com/CitizensDev/Citizens2/issues/1170 or https://github.com/CitizensDev/Citizens2/issues/1332 ?

**Comment by ImHumbug** [comment] 2018-10-12 21:07
Is like #1170 but it just happens with npcs that have the name tag disabled
with /npc name.

**Comment by ImHumbug** [comment] 2018-10-12 23:30
Is like #1170 but it just happens with npcs that have the name tag disabled
with /npc name.

**Comment by ImHumbug** [comment] 2018-10-13 15:48
> Is this equivalent to #1170 or #1332 ?

Is like #1170 but it just happens with npcs that have the name tag disabled
with /npc name.

**Comment by comonier** [comment] 2018-10-15 20:35
same problem here, using last update , i have stop the server, delete folder and jar... with new downloaded file from jekins, and still the problem, lookclose did not work, and reload erase npcs

**Comment by mcmonkey4eva** [comment] 2018-10-15 20:37
@comonier that doesn't sound like the same problem at all?
Any lookclose problem is separate, and `/citizens reload` will only erase NPCs if you did not save (via `/citizens save` or server restart) beforehand.

**Comment by comonier** [comment] 2018-10-15 20:47
my bad i didnt knew about citizens save command. so that should be solved, but the npcs still not looking to players > lookclose command.

**Comment by OpalMoonstride** [comment] 2018-10-21 01:51
Also having this issue. I used /citizens save, and all but the very first, and very last, npc I made, disappear. They're in the citizens list (/npc list) but not in the world.

**Comment by mcmonkey4eva** [comment] 2018-10-21 01:59
@OpalMoonstride You might have this issue: https://github.com/CitizensDev/Citizens2/issues/1332
not the one here.

**Comment by fullwall** [comment] 2018-10-24 07:29
Can't reproduce...

**Comment by mcmonkey4eva** [comment] 2018-10-24 16:06
@ImHumbug can you try going through the steps listed here: https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by BBoyJD10** [comment] 2018-10-25 14:10
STILL HAVE THIS ALSO

**Comment by mcmonkey4eva** [comment] 2018-10-31 04:39
Closing until a reply from @ImHumbug is posted (following my request above).

If anyone else can replicate _specifically_ this issue (as in: an issue relating to `/npc name`) please reply below with information on your situation.
If you have any general troubles with NPCs disappearing after restart - see if it sounds similar to #1332 (relating to chunks that are loaded within the first moments of server starting) and if so, let us know there. If you're pretty sure it can't be that, and it's not related to `/npc name` either, open a new issue with information on your situation.

**Closed** 2018-11-05 05:58 UTC
Labels: Waiting For Reply
