### ISSUE TITLE
NPCs can't enter "true" spectator mode

### ISSUE THREAD

**Issue by Namnodorel** [CitizensDev/Citizens2#1169] opened 2017-06-04 14:18 UTC
Hey,
I'm on spigot `Paper version git-Paper-1071 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`, and use almost the latest version of Citizens (a build of https://github.com/CitizensDev/Citizens2/commit/61c96f08efb654524a1c8be02dc0546c6ec9c5f9). I do not have any plugins installed which could mess with Citizens.

I need to set the gamemode of a player NPC to spectator. But when I use` /npc gamemode 3`, the NPC doesn't go into the real spectator mode, it is just made invisible and, what I really have issues with, does not have noclip (it still can't move through blocks). 

As far as my understanding, Spigot can't differentiate between a real player and an NPC, so I don't see why it would treat the NPC different... On the other hand, searching the repo for stuff related to spectator mode, Citizens doesn't really take care of gamemode handling either.

Any help or ideas would be appreciated.

**Comment by fullwall** [comment] 2017-06-08 12:16
How are you checking the noclip? From what I can see in the code it should be set just the same as a normal player.

**Comment by Namnodorel** [comment] 2017-06-08 12:32
I was writing a plugin in which I need to create a blank NPC, set it into spectator mode and push it around using `setVelocity()`. The NPC wouldn't move through blocks.

And another thing I found when investigating the issue a little further: I already put it on my "The daily WTF"-list, but MC locally only renders  spectators as spectators when they are in the player list. And since most of the time, NPCs shouldn't be shown there, my NPC was not as well.

**Comment by fullwall** [comment] 2017-06-08 12:39
So if you enabled NPCs in the tablist they would show in the local client?

**Comment by Namnodorel** [comment] 2017-06-08 12:41
No, they would show correctly. To a survival player, an NPC in spectator mode was shown no matter what. But to a real player in spectator mode, the NPCs whole body gets rendered (half invisible) when the NPCs aren't in the tablist, and only the head gets rendered (again, only half visible, and this is how it should be), when the NPC is in the tablist.

**Comment by Namnodorel** [comment] 2017-06-08 12:43
Noclip however is not working "naturally" whether the NPC is in the tablist or not.

**Comment by fullwall** [comment] 2017-06-08 12:49
Is EntityPlayer.noclip true?

**Comment by Namnodorel** [comment] 2017-06-08 13:15
No. But `getGameMode()` still returns spectator...

**Comment by fullwall** [comment] 2017-06-09 12:33
Just pushed a fix for the noclip part.

**Comment by Namnodorel** [comment] 2017-06-09 12:37
Ah, nice :) Although it fixes the symptoms, any idea on what the root cause might be? If Spigot doesn't treat players and NPCs the same way on this part, it might as well do somewhere else...

**Comment by fullwall** [comment] 2017-06-09 16:51
Not as yet, but I will look further into it.

**Comment by Namnodorel** [comment] 2017-06-12 13:52
Spigot seems to handle NPC and player movement differently in general... I created a path which I pushed both an NPC and a player along (exactly the same velocity values for both), and then spectated each. It is actually quite a difference: https://youtu.be/9qBXqYMEw54 You can tell that the player moves generally smoother than the NPC, and somehow more accurate (the NPC shouldn't have went through the block at 0:08).

**Comment by Namnodorel** [comment] 2017-06-15 13:55
And even more data: https://puu.sh/wkMZm/7e13049263.png is a graph with the X coordinates of both a player and an NPC when the velocities  are applied. y-axis is the X-Coordinate, x-axis is the ticks. The red line represents the player's coordinates and the green one the coordinates of the NPC. The offset is slight, but noticable.

**Comment by mcmonkey4eva** [comment] 2018-06-28 14:44
Does `Edit: The cause was actually the packet delay, setting it to zero fixed the movement problem.` mean the issue is solved?
If it isn't please reply below (ideally with a summary of where this issue currently stands) and I'll reopen it.

**Closed by mcmonkey4eva** 2018-06-28 14:44 UTC
