### ISSUE TITLE
Many NPCs become "invisible" while others are fine

### ISSUE THREAD

**Issue by ScuroK** [CitizensDev/Citizens2#2919] opened 2022-10-16 10:47 UTC
### `/version` output

```txt
Paper version git-Paper-214 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ec00f99)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2726)
```

### Log file

https://paste.denizenscript.com/View/102304

### config.yml

https://paste.denizenscript.com/View/102305

### saves.yml

https://paste.denizenscript.com/View/102306

### Description

Some NPC's are invisible while some are fine. It does not matter what mob type they are. For example: one villager shows up while another villager does not.
If i create a new npc its there. after i teleport away or restart the server its gone. the affected NPC's will still show up under /npc list. it seems like the plugin thinks they are there.

please notice. the NPC called "test" (in the logfile) . The saves.yml will not show this NPC because i deleted it already before uploading saves.yml. dont be mistaken! If you need a specific NPC that is also affected and is listed in the saves.yml you can take the witch called "Gundula" for example.

thanks in advance.

**Comment by ScuroK** [comment] 2022-10-16 13:04
EDIT : if i create the NPC inside of a spawn chunk and keep the spawn chunks in memory it does not occure.

**Comment by ScuroK** [comment] 2022-10-16 13:10
EDIT 2 : It does not happen with player NPCs only with mob type NPCs

**Comment by mcmonkey4eva** [comment] 2022-10-16 18:44
Considering this a duplicate of #2918

**Closed by mcmonkey4eva** 2022-10-16 18:44 UTC
