### ISSUE TITLE
Getting a WARN after server finishes loading, may be due to latest paper update

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1694] opened 2019-02-05 09:30 UTC
Getting a WARN after server finishes loading, may be due to latest paper update
"Block Entity#remove from being called on Players (commit: 28cf269) (detail / githubweb)"

Paper verison
https://papermc.io/ci/job/Paper-1.13/516/

The WARN

https://pastebin.com/1x6G9LyQ

The output of command `/version` on my server is: **This server is running Paper version git-Paper-516**
The output of command `/version citizens` on my server is: **[19:58:23 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1613)
[19:58:23 INFO]: Website: http://www.citizensnpcs.co
[19:58:23 INFO]: Authors: aPunch and fullwall**

**Comment by mcmonkey4eva** [comment] 2019-02-05 10:06
Duplicate of #1692

**Closed by mcmonkey4eva** 2019-02-05 10:06 UTC
