### ISSUE TITLE
Citizens - low TPS

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#1615] opened 2018-11-11 13:10 UTC
Hello,

I have a performance problem with Citizens. Indeed my server has the Citizens, Sentinel plugin and my TPS is sometimes very low.

I generated a timings and that's what made me realize that the performance problem comes from Citizens.

==> https://timings.aikar.co/?id=fff13ac69ffc48c3a5d95972ea6c9d57

PaperSpigot version :
![image](https://user-images.githubusercontent.com/971712/48313266-1099e900-e5ba-11e8-9148-5c562b8ee48f.png)

Citizens version :
![image](https://user-images.githubusercontent.com/971712/48313270-227b8c00-e5ba-11e8-952a-4ca4567fc492.png)

Sentinel version :
![image](https://user-images.githubusercontent.com/971712/48313280-31623e80-e5ba-11e8-9708-0ef0a2d55103.png)

Server specs :
CPU :  Intel  i7-7700K - 4c/8t - 4,2GHz /4,5GHz
RAM :  64Go DDR4 2400 MHz
SSD :  SoftRaid 2x450Go

Server RAM : 12 GB

NPCs count less than 1500.

Citizens configuration :
https://gist.github.com/Blamo27/b11c70db49cd52d0d96033e4ba2a4a54

Can you help me please ?
Thanks : )

**Comment by Reversiya** [comment] 2018-11-16 01:44
I seem to be getting a similar issue using 

Paperspigot 1.8.8: https://gyazo.com/fb63b69527ba6d285520c7f473648ea7

Citizens version: https://gyazo.com/11771b29ed60bc3dcc8b607c916e9469

Timings: https://gyazo.com/2b48cfd3d0ca2f8b7fcc7e9ab6ed94a6

Server specs :
CPU :  i7-6700K
Server RAM : 10 GB

**Comment by mcmonkey4eva** [comment] 2018-11-16 01:49
@Reversiya you're running nonsensically ancient versions all around... update.

**Comment by Reversiya** [comment] 2018-11-16 05:47
@mcmonkey4eva many major servers run on 1.8 or at the very least support it. Dozens of thousands of dollars are thrown into clientside anticheats for 1.7/1.8. I’m not here to argue, but a lot of major servers operating in pursuit of profit run 1.7-1.8, we all know what happened to shotbow after it removed 1.8 support. Even rpgs like wynncraft support 1.8. 

As for citizens, I’m not too sure if the latest build supports 1.8.8 or not. I just thought I’d throw in the issues I’ve been having recently, maybe help find the cause as i seem to be having the same issue running several versions behind.

**Comment by mergu** [comment] 2018-11-16 06:18
@Reversiya You're 324 citizens builds behind, much more than 'several'. Your build was released in 2015. You can't realistically expect us to step into a time machine to diagnose issues that have probably been solved since then.

As for servers 'supporting' 1.8, your example (wynncraft) runs 1.12.2 and uses plugins such as ViaVersion to provide backsupport for older clients. You can learn more about this here: https://wiki.citizensnpcs.co/Minecraft_1.8 

At this point, four years after the release of 1.8, you should be running 1.12.2 or 1.13.2

**Comment by fullwall** [comment] 2018-11-16 07:17
@Reversiya you should update to the latest Citizens build (it does support 1.8.8) so we can work off the same versions. 

In terms of your issue @Blamo27, is there something else you can use to track performance? Aikar's plugin is not accurate because a lot of PlayerUpdateTask's time is spent within Minecraft internals and not Citizens code but it will be reported as Citizens' fault anyway.

**Comment by Reversiya** [comment] 2018-11-16 07:30
@mergu as I stated before, I am throwing my issue in as it’s an extremely similar situation to the one shown on this issue, meaning it may still be an issue in all 324 build that followed after mine.

It was just a few months ago velt hit 8,000 players, running an entire 1.7 Network. Also viaversion only provides forward support from 1.8, I believe you meant viabackwards or viarewind. 

Demographics on hypixel show 49% use 1.8 while 51% use 1.9+. Badlions demographics showed 98% used 1.7. 1.8 has almost the same amount of players than the 5 versions 1.9-.13 combined. 

I would not mind updating if the community was in favor of updating to .12 or .13, however, there is clearly a large majority that prefer 1.8. 

I’m not demanding you fix this bug or provide support for a build 300 versions behind. I never recall asking for support, a time machine, or a sarcastic response, I claimed I was here to help find the cause since it seems to be quite hard to reproduce if it hasn’t been patched in 3 years.

**Comment by mergu** [comment] 2018-11-16 08:07
We can't know if the issue you are seeing is the same as OP is seeing unless you are running comparable versions (and possibly provide better profiler recordings)

**Comment by Blamo27** [comment] 2018-11-16 08:46
@fullwall Okey, I can do it, what track performance should I use ?

**Comment by fullwall** [comment] 2018-11-16 12:12
@Blamo27 something like warmroast, visualvm, jprofiler, (proper java profilers) would be ideal. They are somewhat difficult to set up however.

@Reversiya the NMS code for 1.8 and 1.12 is completely different, let alone the Citizens code since that build. It's extremely unlikely that this is the same issue. However, if you update to the latest Citizens build and use a proper profiler we can get closer to the root cause of your issue.

**Comment by mcmonkey4eva** [comment] 2018-12-20 16:04
Will reopen when you reply with more info (profiler data as requested above)

**Closed by mcmonkey4eva** 2018-12-20 16:04 UTC
Labels: Help Request, Waiting For Reply
