### ISSUE TITLE
multiselecting

### ISSUE THREAD

**Issue by jandekalkoen** [CitizensDev/Citizens2#2775] opened 2022-03-25 12:02 UTC
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

it would be really nice to be able to control an entire group of npc, like make them follow you and do stuff as 1 group instead of having to select every npc 1 by 1 every time. this would be great for people who use sentinel, to have entire squads follow them with just 1 command instead of 20

**Comment by mcmonkey4eva** [comment] 2022-03-26 01:39
Duplicate of https://github.com/CitizensDev/Citizens2/issues/1281

You can use this Denizen script to accomplish multi-select: https://forum.denizenscript.com/resources/multi-npc-command.58/

`this would be great for people who use sentinel, to have entire squads follow them with just 1 command instead of 20`
for Sentinel usage, it is recommend that you designate one NPC to be a 'leader', and have all the other NPCs follow that leader (or have an NPC follow another NPC that then follows the leader, etc - space them out like that more if you have more NPCs), and then just command the leader to follow you
(if you have 20 NPCs all following you directly, they're gonna be a big bunched up blob mess, if you have them follow in chains, they'll look like they're in some form of actual marching formation)

**Closed by mcmonkey4eva** 2022-03-26 01:39 UTC
