### ISSUE TITLE
Villager NPCs are invisble

### ISSUE THREAD

**Issue by JanisRazen** [CitizensDev/Citizens2#2696] opened 2021-12-01 17:36 UTC
### `/version` output

```txt
Paper: git-Paper-19 (MC: 1.18)
```

### `/version Citizens` output

```txt
Citizens: 2.0.29-Snapshot (build 2416)
```

### Log file

https://paste.denizenscript.com/View/90458

### config.yml

https://paste.denizenscript.com/View/90459

### saves.yml

https://paste.denizenscript.com/View/90460

### Description

Hello!
So I had my already working Citizen NPCs in my 1.17. world, changed to Paper 1.18 dev-build, created a new 1.18 world and used /npc tphere to teleport the NPCs, that were in the old world, to the new world. It worked fine, until they just "disappeared". I'm not entirely sure if I relogged, changed worlds or just flew away, but they are invisible now.
Doing /npc list, they are still there, and if I try to select them with  /npc sel, they get selected.

So they are invisible and not clickable, but appear to be there.

**Comment by baailey** [comment] 2021-12-15 11:36
I am experiencing the same issue. Restarting generally brings them back for me but I'm not sure what triggers the disappearance.

**Comment by jokbon** [comment] 2021-12-18 03:02
I am experiencing the same issue. I suddenly noticed it started messing up citizen names.
I made backtomazes3 which sudenly changed his name to backtoparkour1 and teleported to place where other backtoparkour1 npc was.

so i ended up having 2 backtoparkour1 npc's in same place. but one ansvers being called as backtoparkour1 while other ansvers being called as backtomazes3

**Comment by jokbon** [comment] 2021-12-18 19:11
my coment wasnt out of topic as i described they flew away to other citizens and inherited theyr names. when i aproached spot there was 2 npcs. please try fixing this as i will be forced to move to boring gui's :/

**Comment by Getblock** [comment] 2021-12-23 13:26
I believe that I am also experiencing the same exact issue. .. According to configs and npc commands, the NPC/s exist but they are not interactable and visually not there. 

Paper 1.18.1 ver 81
Citizens2 Build2430

**Comment by mcmonkey4eva** [comment] 2021-12-23 13:34
@RazenHD Does this issue still occur for you in 1.18.1? Also, have you tried `/npc tp` to teleport yourself *to* the NPC, in case it's just been moved to a different location?
Your log file was full of random error messages from other plugins, which will *seemingly* unrelated might actually have caused the issue indirectly.
If you're still getting the issue on an up-to-date server, can you please post updated logs?

@Getblock do you actually have the same specific situation of having multiple worlds, transferred teleported NPCs from one world to another, and then they disappeared? If not, you're more likely to have a different but merely similar problem.

@baailey same question to you as to Getblock.

**Comment by Getblock** [comment] 2021-12-24 08:04
After doing some experimentation on the NPCs to figure out why they are becoming invisible after server restarts.. We've somehow found out that setting the "Type" of the NPC to a "Villager" is the issue. We're not exactly sure the reason for that but after converting every NPC on server to a "player" type, this issue has stopped occurring for me.

**Comment by Neeekss** [comment] 2021-12-25 14:52
Same for me half NPC with villager type is disappeared.

**Comment by RSLuke** [comment] 2021-12-28 13:11
Same here, some npcs with type villager or vindicator are disappearing, always the 2 same, have to manually /citizens reload everytime

**Comment by mcmonkey4eva** [comment] 2021-12-28 13:16
Not convinced yall 3 are necessarily hitting the same issue as the original user, since they haven't specified, but since they're not replying, could at least one of you three please post a current `latest.log` from a server that's experiencing the issue?

Also please try to narrow down when your villager NPCs are disappearing specifically (is it a specific duration of time? Does it relate to an event from another plugin? Is it after you use a certain command?)

**Comment by RSLuke** [comment] 2021-12-28 13:21
I have 44 npcs on my server, 2 of them disappear every daily reboot but are not removed from the file since I can make them come back with the citizens reload comand
I don't have anything in the logs but I'll check once more
The 2 npcs are villager and vindicator type
[05:04:59] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.29-SNAPSHOT (build 2428)
[05:05:24] [Server thread/INFO]: [Citizens] Loaded 44 NPCs.

**Comment by fullwall** [comment] 2021-12-28 13:40
Also enable citizens debug to at least log despawns/respawns.

**Comment by RSLuke** [comment] 2021-12-28 14:07
As requested :
`[14:43:06] [Server thread/INFO]: [Citizens] Tried to despawn 70 while already despawned, DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Tried to despawn 69 while already despawned, DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Tried to despawn 68 while already despawned, DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Tried to despawn 67 while already despawned, DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 66 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 66 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Tried to despawn 65 while already despawned, DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 64 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 64 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 62 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 62 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 41 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 41 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 39 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 39 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 38 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 38 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 37 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 37 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 36 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 36 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 35 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 35 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Tried to despawn 34 while already despawned, DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Tried to despawn 33 while already despawned, DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 32 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 32 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 31 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 31 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Tried to despawn 30 while already despawned, DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 29 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 29 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 28 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 28 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 27 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 27 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 26 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 26 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 25 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 25 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 22 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 22 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 21 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 21 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 20 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 20 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 18 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 18 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 17 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 17 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 16 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 16 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 15 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 15 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 14 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 14 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 13 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 13 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 12 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 12 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 11 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 11 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 10 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 10 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 9 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 9 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 8 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 8 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 7 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 7 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 6 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 6 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 4 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 4 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 2 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 2 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 1 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 1 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 0 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 0 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Preventing further respawns of 0 due to DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 0 DespawnReason.RELOAD
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 4 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 4 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 2 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 2 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 1 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 1 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 0 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 0 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 10 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 10 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 9 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 9 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 8 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 8 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 7 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 7 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 6 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 6 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 18 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 18 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 17 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 17 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 16 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 16 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 15 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 15 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 14 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 14 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 13 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 13 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 12 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 12 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 11 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 11 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 21 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 21 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 20 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 20 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 22 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 22 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 25 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 25 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 32 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 32 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 31 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 31 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 29 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 29 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 28 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 28 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 27 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 27 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 26 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 26 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 36 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 36 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 35 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 35 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 39 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 0 due to SpawnReason.PLUGIN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 0 SpawnReason.PLUGIN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 39 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 38 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 38 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 37 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 37 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 41 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 41 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 62 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 62 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 64 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 64 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Retrying spawn of 65 later, SpawnReason.RESPAWN. Was loaded false is loaded false
[14:43:06] [Server thread/INFO]: [Citizens] Stored 65 for respawn from NPCNeedsRespawnEvent
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 70 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 70 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Retrying spawn of 69 later, SpawnReason.RESPAWN. Was loaded false is loaded false
[14:43:06] [Server thread/INFO]: [Citizens] Stored 69 for respawn from NPCNeedsRespawnEvent
[14:43:06] [Server thread/INFO]: [Citizens] Retrying spawn of 68 later, SpawnReason.RESPAWN. Was loaded false is loaded false
[14:43:06] [Server thread/INFO]: [Citizens] Stored 68 for respawn from NPCNeedsRespawnEvent
[14:43:06] [Server thread/INFO]: [Citizens] Retrying spawn of 67 later, SpawnReason.RESPAWN. Was loaded false is loaded false
[14:43:06] [Server thread/INFO]: [Citizens] Stored 67 for respawn from NPCNeedsRespawnEvent
[14:43:06] [Server thread/INFO]: [Citizens] Removing respawns of 66 due to SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Spawned 66 SpawnReason.RESPAWN
[14:43:06] [Server thread/INFO]: [Citizens] Removing 70 from skin tracker due to DespawnReason.CHUNK_UNLOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned 70 DespawnReason.CHUNK_UNLOAD
[14:43:06] [Server thread/INFO]: [Citizens] Despawned id 70 due to chunk unload at [-63,3]
[14:43:07] [Server thread/INFO]: Junior_Fork issued server command: /lieux
[14:43:08] [Server thread/INFO]: Junior_Fork a été téléporté à (Noel_2021,186,64,31).
[14:43:08] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5086ms or 101 ticks behind
[14:43:08] [Server thread/INFO]: [Citizens] Respawning all NPCs at [7,0] due to org.bukkit.event.world.ChunkLoadEvent@a2131a8e
[14:43:08] [Server thread/INFO]: [Citizens] Removing respawns of 69 due to SpawnReason.CHUNK_LOAD
[14:43:08] [Server thread/INFO]: [Citizens] Spawned 69 SpawnReason.CHUNK_LOAD
[14:43:08] [Server thread/INFO]: [Citizens] Spawned id 69 during org.bukkit.event.world.ChunkLoadEvent@a2131a8e at [7,0]
[14:43:08] [Server thread/INFO]: [Citizens] Removing respawns of 68 due to SpawnReason.CHUNK_LOAD
[14:43:08] [Server thread/INFO]: [Citizens] Removing respawns of 0 due to SpawnReason.PLUGIN
[14:43:08] [Server thread/INFO]: [Citizens] Spawned 0 SpawnReason.PLUGIN
[14:43:08] [Server thread/INFO]: [Citizens] Spawned 68 SpawnReason.CHUNK_LOAD
[14:43:08] [Server thread/INFO]: [Citizens] Spawned id 68 during org.bukkit.event.world.ChunkLoadEvent@a2131a8e at [7,0]
[14:43:08] [Server thread/INFO]: [Citizens] Respawning all NPCs at [8,0] due to org.bukkit.event.world.ChunkLoadEvent@a45cab43
[14:43:08] [Server thread/INFO]: [Citizens] Removing respawns of 65 due to SpawnReason.CHUNK_LOAD
[14:43:08] [Server thread/INFO]: [Citizens] Spawned 65 SpawnReason.CHUNK_LOAD
[14:43:08] [Server thread/INFO]: [Citizens] Spawned id 65 during org.bukkit.event.world.ChunkLoadEvent@a45cab43 at [8,0]
`

**Comment by fullwall** [comment] 2021-12-28 14:08
Missing the startup log, as well as the ID of the relevant NPC.

**Comment by RSLuke** [comment] 2021-12-28 14:12
Anything related to Citizens :
[05:04:48] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.29-SNAPSHOT (build 2428)
[05:04:59] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.29-SNAPSHOT (build 2428)
[05:04:59] [Server thread/INFO]: [GCore-8.33.0] Enabled integration for Citizens
[05:05:04] [Server thread/INFO]: [QuestCreator-6.33.1] Enabled integration for Citizens
[05:05:18] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[05:05:18] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[05:05:18] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[05:05:18] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[05:05:18] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[05:05:18] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[05:05:18] [Server thread/INFO]: _______________________________________________________
[05:05:18] [Server thread/INFO]:   Integrating PaperSpigot async methods
[05:05:18] [Server thread/INFO]:   Citizens found.
[05:05:24] [Server thread/INFO]: [Citizens] Loaded 44 NPCs.
NPC IDs : 64 and 70

**Comment by bipedd** [comment] 2022-01-01 10:57
Getting this issue with player citizens as well.

**Comment by mcmonkey4eva** [comment] 2022-01-01 11:19
Still waiting for anybody to post full `logs/latest.log` relevant to the issue.

**Comment by jokbon** [comment] 2022-01-01 14:07
I posted full log multiple times in your discord.
Heres non full log of plugin behavior.
My worlds developer added citizens 2 as soft dependency at my request.
And yes npcs still act weird at worlds provided by folowing plugins: multiverse & my worlds.

>:(

[02:20:48] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.18.1-v1
[02:20:57] [Server thread/INFO]: [My_Worlds] Loading My_Worlds v1.18.1-v2-SNAPSHOT
[02:20:57] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.29-SNAPSHOT (build 2422)
[02:21:00] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.18.1-v1
[02:21:05] [Server thread/INFO]: [My_Worlds] Enabling My_Worlds v1.18.1-v2-SNAPSHOT
[02:21:05] [Server thread/INFO]: [My_Worlds] Loading world 'VD-Quarry'
[02:21:06] [Server thread/INFO]: [My_Worlds] Loading world 'TB-Forest'
[02:21:06] [Server thread/INFO]: [My_Worlds] Loading world 'MM-Offices'
[02:21:06] [Server thread/INFO]: [My_Worlds] Loading world 'MM-HountedHouse'
[02:21:06] [Server thread/INFO]: [My_Worlds] Loading world 'Parkour' using chunk generator: ':minecraft:air;minecraft:the_void'
[02:21:06] [Server thread/INFO]: [My_Worlds] Loading world 'MM-SantaFactory'
[02:21:06] [Server thread/INFO]: [My_Worlds] Loading world 'TB-Fortress'
[02:21:06] [Server thread/INFO]: [My_Worlds] Loading world 'Maze' using chunk generator: ':minecraft:air;minecraft:the_void'
[02:21:06] [Server thread/INFO]: [My_Worlds] My_Worlds version 1.18.1-v2-SNAPSHOT (build: NO-CI) enabled! (0.927s)
[02:21:07] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.29-SNAPSHOT (build 2422)
[02:21:08] [Server thread/INFO]: [Citizens] Loaded 27 NPCs.

**Comment by baailey** [comment] 2022-01-20 03:19
Hello, not sure if this issue will still be looked at due to being closed, but today 4 of my villager NPCs have disappeared. Here is the latest log: https://mcpaste.io/1801e31f3a99c927

Although I'n running build 2419, I'll be updating to build 2454 when the server automatically restarts in 12 hours. I'll post an update if they're or not when I can.

**Comment by mcmonkey4eva** [comment] 2022-01-20 08:44
Please use https://paste.denizenscript.com/New/Log to paste logs

**Comment by baailey** [comment] 2022-01-20 15:13
the 4 villager npcs are still missing https://paste.denizenscript.com/View/92411

**Comment by baailey** [comment] 2022-01-27 10:50
If you need any other information, please let me know. I'd like to get this fixed as soon as possible.

**Comment by fullwall** [comment] 2022-02-14 16:35
Can you provide logs with at least citizens debug enabled??

**Comment by baailey** [comment] 2022-02-28 06:20
Sorry for the delay, I hope this has the info you're after https://paste.denizenscript.com/View/93891

**Comment by WarnDa** [comment] 2022-05-22 12:29
Any news ?

**Comment by BehrRiley** [comment] 2022-05-22 12:31
> Any news ?

Fullwall had requested above for logs with the debug mode enabled; Can you replicate the issue starting from scratch after enabling the debug mode in the config?

**Comment by Thin-Troll** [comment] 2022-06-26 21:32
https://github.com/CitizensDev/Citizens2/issues/2821

**Comment by fullwall** [comment] 2022-06-27 04:10
Since another person has reported this; still waiting for consistently reproducible steps ideally with a citizens debug log and IDs of the affected NPCs.

**Comment by Thin-Troll** [comment] 2022-06-27 17:29
> Since another person has reported this; still waiting for consistently reproducible steps ideally with a citizens debug log and IDs of the affected NPCs.

what exactly is required?
what logs and debugs, can you describe the actions in detail?
my residents disappear every reboot, I can easily show and repeat that the residents are not visible

**Comment by fullwall** [comment] 2022-06-27 23:28
Enable citizens debug in settings
Tell me which IDs are affected
Post a log including after the point the villagers disappear
Ideally this would be on a test server with only citizens installed

**Comment by mcmonkey4eva** [comment] 2022-07-03 06:57
After some followup from a user on Discord seeing this issue got a good lead, this commit: <https://github.com/CitizensDev/Citizens2/commit/dfbdfaed0954684d00520389f9c7ea98a8e9e186> adds a config setting that lets you configure lag compensation (compensates for a lag-related bug on modern Paper servers).

So for those replicating the issue in this thread, try updating to the latest Citizens dev build from <https://ci.citizensnpcs.co/job/Citizens2/>, then edit your `config.yml` to raise `general.entity-spawn-wait-ticks` to a higher value like 20 or 30, and see if it reduces the issue.

**Comment by Diamondback88** [comment] 2022-08-01 02:03
> Member

Tried this on multiple settings for my server, and villager NPCs still are invisible upon restart.

**Comment by SaltyAimbOtter** [comment] 2022-08-02 21:32
Apparently we just discovered reliable steps to reproduce this in [BetonQuest#1974](https://github.com/BetonQuest/BetonQuest/issues/1974#issuecomment-1203202892).
Without the BQ related stuff, this is the way for us to reproduce this issue with **pigs**:
Versions in use:
Citizens `2.0.30-SNAPSHOT-2658`
Paper `1.19.1-97`

1. `/npc create TestNPC`
2. `/npc type pig`
3. `/citizens save`
4. Restart server

5. 🪄 NPC is now invisible 🪄 
  * `/npc tp` teleports me to the correct location.
  * `/npc sel` does NOT correctly select the NPC.
  * `/npc tphere` spawns the NPC.
  
The workaround with `general.entity-spawn-wait-ticks` does seem to work for me.
[debuglog.txt](https://github.com/CitizensDev/Citizens2/files/9245816/debuglog.txt)

**Comment by fullwall** [comment] 2022-08-02 21:45
...why was entity-spawn-wait-ticks set to 1?

**Comment by SaltyAimbOtter** [comment] 2022-08-03 07:11
I set it to one so I could get a log of it happening faster. Happens with the default value as well.

**Comment by fullwall** [comment] 2023-04-02 17:37
Still unable to reproduce this. Any update?

**Comment by Olif666** [comment] 2023-04-16 15:22
I'm having a different problem here. The only type of npc that's invisible is player. I'm using the most recent version of citizens.

**Comment by Olif666** [comment] 2023-04-16 15:23
> 

It seems to be a conflict with TAB plugin

**Comment by fullwall** [comment] 2024-09-15 18:01
Seeing as I have not been able to reproduce this, going to close this pending better reproduction steps.

**Closed by fullwall** 2024-09-15 18:01 UTC
Labels: Bug Report
