### ISSUE TITLE
Could not pass event ChunkUnloadEven

### ISSUE THREAD

**Issue by banit** [CitizensDev/Citizens2#2097] opened 2020-04-10 12:45 UTC
ERROR 14:41:46
Could not pass event ChunkUnloadEvent to Citizens v2.0.26-SNAPSHOT (build 1854)
Console 14:41:46
java.lang.IllegalStateException: Removing entity while ticking!
at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1484) ~[patched_1.15.2.jar:git-Paper-167]
at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.removeFromWorld(NMSImpl.java:927) ~[?:?]
at net.citizensnpcs.util.NMS.removeFromWorld(NMS.java:334) ~[?:?]
at net.citizensnpcs.nms.v1_15_R1.entity.HumanController.remove(HumanController.java:116) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:100) ~[?:?]
at net.citizensnpcs.EventListen$2.run(EventListen.java:174) ~[?:?]
at net.citizensnpcs.EventListen.onChunkUnload(EventListen.java:206) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor207.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-167]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-167]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-167]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.Chunk.unloadCallback(Chunk.java:696) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:383) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:105) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.PlayerChunk.a(PlayerChunk.java:393) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:100) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:510) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.access$200(ChunkProviderServer.java:22) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:908) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1030) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:477) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1260) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1127) ~[patched_1.15.2.jar:git-Paper-167]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:935) ~[patched_1.15.2.jar:git-Paper-167]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

Citizens v2.0.25 build 1854
paper 167 - 1.15.2-R0.1

**Comment by mcmonkey4eva** [comment] 2020-04-10 16:15
Duplicate of https://github.com/CitizensDev/Citizens2/issues/2098

**Closed by mcmonkey4eva** 2020-04-10 16:15 UTC
